#!/bin/bash
#                                                       -*-shell-script-*-

# Skip the hm2-idrom test if not running kernel threads and the
# hostmot2.so module doesn't exist for this flavor

test -f $EMC2_HOME/rtlib/modules/hostmot2.so
