/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_CANON_NPB_H_INCLUDED
#define PB_CANON_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#include "machinetalk/protobuf/types.npb.h"
#include "machinetalk/protobuf/emcclass.npb.h"
#include "machinetalk/protobuf/motcmds.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _machinetalk_Emc_Exec_Plugin_Ca1l {
    pb_callback_t call;
} machinetalk_Emc_Exec_Plugin_Ca1l;

typedef struct _machinetalk_Emc_Io_Plugin_Call {
    pb_callback_t call;
} machinetalk_Emc_Io_Plugin_Call;

typedef struct _machinetalk_Emc_Aux_Input_Wait {
    uint32_t index;
    machinetalk_InputType input_type;
    machinetalk_WaitType wait_type;
    double timeout;
} machinetalk_Emc_Aux_Input_Wait;

typedef struct _machinetalk_Emc_Motion_Adaptive {
    bool status;
} machinetalk_Emc_Motion_Adaptive;

typedef struct _machinetalk_Emc_Motion_Set_Aout {
    uint32_t index;
    double start;
    double end;
    bool now;
} machinetalk_Emc_Motion_Set_Aout;

typedef struct _machinetalk_Emc_Motion_Set_Dout {
    uint32_t index;
    bool start;
    bool end;
    bool now;
} machinetalk_Emc_Motion_Set_Dout;

typedef struct _machinetalk_Emc_Operator_Display {
    int32_t id;
    pb_callback_t display;
} machinetalk_Emc_Operator_Display;

typedef struct _machinetalk_Emc_Operator_Error {
    int32_t id;
    pb_callback_t error;
} machinetalk_Emc_Operator_Error;

typedef struct _machinetalk_Emc_Operator_Text {
    int32_t id;
    pb_callback_t text;
} machinetalk_Emc_Operator_Text;

typedef struct _machinetalk_Emc_Spindle_On {
    double speed;
    double factor;
    double xoffset;
} machinetalk_Emc_Spindle_On;

typedef struct _machinetalk_Emc_Spindle_Orient {
    double orientation;
    machinetalk_CanonDirection mode;
} machinetalk_Emc_Spindle_Orient;

typedef struct _machinetalk_Emc_Spindle_Speed {
    double speed;
    double factor;
    double xoffset;
} machinetalk_Emc_Spindle_Speed;

typedef struct _machinetalk_Emc_Spindle_Wait_Orient_Complete {
    double timeout;
} machinetalk_Emc_Spindle_Wait_Orient_Complete;

typedef struct _machinetalk_Emc_Tool_Prepare {
    int32_t pocket;
    int32_t tool;
} machinetalk_Emc_Tool_Prepare;

typedef struct _machinetalk_Emc_Tool_Set_Number {
    int32_t tool;
} machinetalk_Emc_Tool_Set_Number;

typedef struct _machinetalk_Emc_Tool_Set_Offset {
    int32_t pocket;
    int32_t toolno;
    machinetalk_EmcPose offset;
    double diameter;
    double frontangle;
    double backangle;
    int32_t orientation;
} machinetalk_Emc_Tool_Set_Offset;

typedef struct _machinetalk_Emc_Traj_Circular_Move {
    machinetalk_MotionType type;
    machinetalk_EmcPose end;
    machinetalk_PmCartesian center;
    machinetalk_PmCartesian normal;
    double vel;
    double ini_maxvel;
    double acc;
    bool feed_mode;
    int32_t turn;
} machinetalk_Emc_Traj_Circular_Move;

typedef struct _machinetalk_Emc_Traj_Delay {
    double delay;
} machinetalk_Emc_Traj_Delay;

typedef struct _machinetalk_Emc_Traj_Linear_Move {
    machinetalk_MotionType type;
    machinetalk_EmcPose end;
    double vel;
    double ini_maxvel;
    double acc;
    bool feed_mode;
    int32_t indexrotary;
} machinetalk_Emc_Traj_Linear_Move;

typedef struct _machinetalk_Emc_Traj_Probe {
    machinetalk_MotionType type;
    machinetalk_EmcPose pos;
    double vel;
    double ini_maxvel;
    double acc;
    uint32_t probe_type;
} machinetalk_Emc_Traj_Probe;

typedef struct _machinetalk_Emc_Traj_Rigid_Tap {
    machinetalk_EmcPose pos;
    double vel;
    double ini_maxvel;
    double acc;
} machinetalk_Emc_Traj_Rigid_Tap;

typedef struct _machinetalk_Emc_Traj_Set_Fh_Enable {
    bool mode;
} machinetalk_Emc_Traj_Set_Fh_Enable;

typedef struct _machinetalk_Emc_Traj_Set_Fo_Enable {
    bool mode;
} machinetalk_Emc_Traj_Set_Fo_Enable;

typedef struct _machinetalk_Emc_Traj_Set_G5x {
    machinetalk_EmcPose origin;
    machinetalk_OriginIndex g5x_index;
} machinetalk_Emc_Traj_Set_G5x;

typedef struct _machinetalk_Emc_Traj_Set_G92 {
    machinetalk_EmcPose origin;
} machinetalk_Emc_Traj_Set_G92;

typedef struct _machinetalk_Emc_Traj_Set_Offset {
    machinetalk_EmcPose offset;
} machinetalk_Emc_Traj_Set_Offset;

typedef struct _machinetalk_Emc_Traj_Set_Rotation {
    double rotation;
} machinetalk_Emc_Traj_Set_Rotation;

typedef struct _machinetalk_Emc_Traj_Set_So_Enable {
    bool mode;
} machinetalk_Emc_Traj_Set_So_Enable;

typedef struct _machinetalk_Emc_Traj_Set_Spindlesync {
    double feed_per_revolution;
    bool velocity_mode;
} machinetalk_Emc_Traj_Set_Spindlesync;

typedef struct _machinetalk_Emc_Traj_Set_Term_Cond {
    machinetalk_TermConditionType cond;
    double tolerance;
} machinetalk_Emc_Traj_Set_Term_Cond;

/* Default values for struct fields */
extern const double machinetalk_Emc_Spindle_On_speed_default;
extern const double machinetalk_Emc_Spindle_On_factor_default;
extern const double machinetalk_Emc_Spindle_On_xoffset_default;

/* Initializer values for message structs */
#define machinetalk_Emc_Traj_Set_G5x_init_default {machinetalk_EmcPose_init_default, (machinetalk_OriginIndex)0}
#define machinetalk_Emc_Traj_Set_G92_init_default {machinetalk_EmcPose_init_default}
#define machinetalk_Emc_Traj_Set_Rotation_init_default {0}
#define machinetalk_Emc_Traj_Linear_Move_init_default {(machinetalk_MotionType)0, machinetalk_EmcPose_init_default, 0, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Probe_init_default  {(machinetalk_MotionType)0, machinetalk_EmcPose_init_default, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Circular_Move_init_default {(machinetalk_MotionType)0, machinetalk_EmcPose_init_default, machinetalk_PmCartesian_init_default, machinetalk_PmCartesian_init_default, 0, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Rigid_Tap_init_default {machinetalk_EmcPose_init_default, 0, 0, 0}
#define machinetalk_Emc_Traj_Set_Term_Cond_init_default {(machinetalk_TermConditionType)0, 0}
#define machinetalk_Emc_Traj_Set_Spindlesync_init_default {0, 0}
#define machinetalk_Emc_Traj_Delay_init_default  {0}
#define machinetalk_Emc_Spindle_On_init_default  {0, 0, 0}
#define machinetalk_Emc_Spindle_Speed_init_default {0, 0, 0}
#define machinetalk_Emc_Spindle_Orient_init_default {0, (machinetalk_CanonDirection)0}
#define machinetalk_Emc_Spindle_Wait_Orient_Complete_init_default {0}
#define machinetalk_Emc_Tool_Set_Offset_init_default {0, 0, machinetalk_EmcPose_init_default, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Set_Offset_init_default {machinetalk_EmcPose_init_default}
#define machinetalk_Emc_Tool_Prepare_init_default {0, 0}
#define machinetalk_Emc_Tool_Set_Number_init_default {0}
#define machinetalk_Emc_Traj_Set_Fo_Enable_init_default {0}
#define machinetalk_Emc_Traj_Set_So_Enable_init_default {0}
#define machinetalk_Emc_Traj_Set_Fh_Enable_init_default {0}
#define machinetalk_Emc_Motion_Adaptive_init_default {0}
#define machinetalk_Emc_Operator_Display_init_default {0, {{NULL}, NULL}}
#define machinetalk_Emc_Operator_Text_init_default {0, {{NULL}, NULL}}
#define machinetalk_Emc_Operator_Error_init_default {0, {{NULL}, NULL}}
#define machinetalk_Emc_Motion_Set_Dout_init_default {0, 0, 0, 0}
#define machinetalk_Emc_Motion_Set_Aout_init_default {0, 0, 0, 0}
#define machinetalk_Emc_Aux_Input_Wait_init_default {0, (machinetalk_InputType)0, (machinetalk_WaitType)0, 0}
#define machinetalk_Emc_Exec_Plugin_Ca1l_init_default {{{NULL}, NULL}}
#define machinetalk_Emc_Io_Plugin_Call_init_default {{{NULL}, NULL}}
#define machinetalk_Emc_Traj_Set_G5x_init_zero   {machinetalk_EmcPose_init_zero, (machinetalk_OriginIndex)0}
#define machinetalk_Emc_Traj_Set_G92_init_zero   {machinetalk_EmcPose_init_zero}
#define machinetalk_Emc_Traj_Set_Rotation_init_zero {0}
#define machinetalk_Emc_Traj_Linear_Move_init_zero {(machinetalk_MotionType)0, machinetalk_EmcPose_init_zero, 0, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Probe_init_zero     {(machinetalk_MotionType)0, machinetalk_EmcPose_init_zero, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Circular_Move_init_zero {(machinetalk_MotionType)0, machinetalk_EmcPose_init_zero, machinetalk_PmCartesian_init_zero, machinetalk_PmCartesian_init_zero, 0, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Rigid_Tap_init_zero {machinetalk_EmcPose_init_zero, 0, 0, 0}
#define machinetalk_Emc_Traj_Set_Term_Cond_init_zero {(machinetalk_TermConditionType)0, 0}
#define machinetalk_Emc_Traj_Set_Spindlesync_init_zero {0, 0}
#define machinetalk_Emc_Traj_Delay_init_zero     {0}
#define machinetalk_Emc_Spindle_On_init_zero     {0, 0, 0}
#define machinetalk_Emc_Spindle_Speed_init_zero  {0, 0, 0}
#define machinetalk_Emc_Spindle_Orient_init_zero {0, (machinetalk_CanonDirection)0}
#define machinetalk_Emc_Spindle_Wait_Orient_Complete_init_zero {0}
#define machinetalk_Emc_Tool_Set_Offset_init_zero {0, 0, machinetalk_EmcPose_init_zero, 0, 0, 0, 0}
#define machinetalk_Emc_Traj_Set_Offset_init_zero {machinetalk_EmcPose_init_zero}
#define machinetalk_Emc_Tool_Prepare_init_zero   {0, 0}
#define machinetalk_Emc_Tool_Set_Number_init_zero {0}
#define machinetalk_Emc_Traj_Set_Fo_Enable_init_zero {0}
#define machinetalk_Emc_Traj_Set_So_Enable_init_zero {0}
#define machinetalk_Emc_Traj_Set_Fh_Enable_init_zero {0}
#define machinetalk_Emc_Motion_Adaptive_init_zero {0}
#define machinetalk_Emc_Operator_Display_init_zero {0, {{NULL}, NULL}}
#define machinetalk_Emc_Operator_Text_init_zero  {0, {{NULL}, NULL}}
#define machinetalk_Emc_Operator_Error_init_zero {0, {{NULL}, NULL}}
#define machinetalk_Emc_Motion_Set_Dout_init_zero {0, 0, 0, 0}
#define machinetalk_Emc_Motion_Set_Aout_init_zero {0, 0, 0, 0}
#define machinetalk_Emc_Aux_Input_Wait_init_zero {0, (machinetalk_InputType)0, (machinetalk_WaitType)0, 0}
#define machinetalk_Emc_Exec_Plugin_Ca1l_init_zero {{{NULL}, NULL}}
#define machinetalk_Emc_Io_Plugin_Call_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_Emc_Exec_Plugin_Ca1l_call_tag 20
#define machinetalk_Emc_Io_Plugin_Call_call_tag  20
#define machinetalk_Emc_Aux_Input_Wait_index_tag 10
#define machinetalk_Emc_Aux_Input_Wait_input_type_tag 20
#define machinetalk_Emc_Aux_Input_Wait_wait_type_tag 30
#define machinetalk_Emc_Aux_Input_Wait_timeout_tag 40
#define machinetalk_Emc_Motion_Adaptive_status_tag 10
#define machinetalk_Emc_Motion_Set_Aout_index_tag 10
#define machinetalk_Emc_Motion_Set_Aout_start_tag 20
#define machinetalk_Emc_Motion_Set_Aout_end_tag  30
#define machinetalk_Emc_Motion_Set_Aout_now_tag  40
#define machinetalk_Emc_Motion_Set_Dout_index_tag 10
#define machinetalk_Emc_Motion_Set_Dout_start_tag 20
#define machinetalk_Emc_Motion_Set_Dout_end_tag  30
#define machinetalk_Emc_Motion_Set_Dout_now_tag  40
#define machinetalk_Emc_Operator_Display_id_tag  10
#define machinetalk_Emc_Operator_Display_display_tag 20
#define machinetalk_Emc_Operator_Error_id_tag    10
#define machinetalk_Emc_Operator_Error_error_tag 20
#define machinetalk_Emc_Operator_Text_id_tag     10
#define machinetalk_Emc_Operator_Text_text_tag   20
#define machinetalk_Emc_Spindle_On_speed_tag     10
#define machinetalk_Emc_Spindle_On_factor_tag    20
#define machinetalk_Emc_Spindle_On_xoffset_tag   30
#define machinetalk_Emc_Spindle_Orient_orientation_tag 10
#define machinetalk_Emc_Spindle_Orient_mode_tag  20
#define machinetalk_Emc_Spindle_Speed_speed_tag  10
#define machinetalk_Emc_Spindle_Speed_factor_tag 20
#define machinetalk_Emc_Spindle_Speed_xoffset_tag 30
#define machinetalk_Emc_Spindle_Wait_Orient_Complete_timeout_tag 10
#define machinetalk_Emc_Tool_Prepare_pocket_tag  10
#define machinetalk_Emc_Tool_Prepare_tool_tag    20
#define machinetalk_Emc_Tool_Set_Number_tool_tag 10
#define machinetalk_Emc_Tool_Set_Offset_pocket_tag 10
#define machinetalk_Emc_Tool_Set_Offset_toolno_tag 15
#define machinetalk_Emc_Tool_Set_Offset_offset_tag 20
#define machinetalk_Emc_Tool_Set_Offset_diameter_tag 30
#define machinetalk_Emc_Tool_Set_Offset_frontangle_tag 40
#define machinetalk_Emc_Tool_Set_Offset_backangle_tag 50
#define machinetalk_Emc_Tool_Set_Offset_orientation_tag 60
#define machinetalk_Emc_Traj_Circular_Move_type_tag 10
#define machinetalk_Emc_Traj_Circular_Move_end_tag 20
#define machinetalk_Emc_Traj_Circular_Move_center_tag 25
#define machinetalk_Emc_Traj_Circular_Move_normal_tag 27
#define machinetalk_Emc_Traj_Circular_Move_vel_tag 30
#define machinetalk_Emc_Traj_Circular_Move_ini_maxvel_tag 40
#define machinetalk_Emc_Traj_Circular_Move_acc_tag 50
#define machinetalk_Emc_Traj_Circular_Move_feed_mode_tag 60
#define machinetalk_Emc_Traj_Circular_Move_turn_tag 70
#define machinetalk_Emc_Traj_Delay_delay_tag     10
#define machinetalk_Emc_Traj_Linear_Move_type_tag 10
#define machinetalk_Emc_Traj_Linear_Move_end_tag 20
#define machinetalk_Emc_Traj_Linear_Move_vel_tag 30
#define machinetalk_Emc_Traj_Linear_Move_ini_maxvel_tag 40
#define machinetalk_Emc_Traj_Linear_Move_acc_tag 50
#define machinetalk_Emc_Traj_Linear_Move_feed_mode_tag 60
#define machinetalk_Emc_Traj_Linear_Move_indexrotary_tag 70
#define machinetalk_Emc_Traj_Probe_type_tag      10
#define machinetalk_Emc_Traj_Probe_pos_tag       20
#define machinetalk_Emc_Traj_Probe_vel_tag       30
#define machinetalk_Emc_Traj_Probe_ini_maxvel_tag 40
#define machinetalk_Emc_Traj_Probe_acc_tag       50
#define machinetalk_Emc_Traj_Probe_probe_type_tag 60
#define machinetalk_Emc_Traj_Rigid_Tap_pos_tag   20
#define machinetalk_Emc_Traj_Rigid_Tap_vel_tag   30
#define machinetalk_Emc_Traj_Rigid_Tap_ini_maxvel_tag 40
#define machinetalk_Emc_Traj_Rigid_Tap_acc_tag   50
#define machinetalk_Emc_Traj_Set_Fh_Enable_mode_tag 10
#define machinetalk_Emc_Traj_Set_Fo_Enable_mode_tag 10
#define machinetalk_Emc_Traj_Set_G5x_origin_tag  10
#define machinetalk_Emc_Traj_Set_G5x_g5x_index_tag 20
#define machinetalk_Emc_Traj_Set_G92_origin_tag  10
#define machinetalk_Emc_Traj_Set_Offset_offset_tag 10
#define machinetalk_Emc_Traj_Set_Rotation_rotation_tag 10
#define machinetalk_Emc_Traj_Set_So_Enable_mode_tag 10
#define machinetalk_Emc_Traj_Set_Spindlesync_feed_per_revolution_tag 10
#define machinetalk_Emc_Traj_Set_Spindlesync_velocity_mode_tag 20
#define machinetalk_Emc_Traj_Set_Term_Cond_cond_tag 10
#define machinetalk_Emc_Traj_Set_Term_Cond_tolerance_tag 20

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_Emc_Traj_Set_G5x_fields[3];
extern const pb_field_t machinetalk_Emc_Traj_Set_G92_fields[2];
extern const pb_field_t machinetalk_Emc_Traj_Set_Rotation_fields[2];
extern const pb_field_t machinetalk_Emc_Traj_Linear_Move_fields[8];
extern const pb_field_t machinetalk_Emc_Traj_Probe_fields[7];
extern const pb_field_t machinetalk_Emc_Traj_Circular_Move_fields[10];
extern const pb_field_t machinetalk_Emc_Traj_Rigid_Tap_fields[5];
extern const pb_field_t machinetalk_Emc_Traj_Set_Term_Cond_fields[3];
extern const pb_field_t machinetalk_Emc_Traj_Set_Spindlesync_fields[3];
extern const pb_field_t machinetalk_Emc_Traj_Delay_fields[2];
extern const pb_field_t machinetalk_Emc_Spindle_On_fields[4];
extern const pb_field_t machinetalk_Emc_Spindle_Speed_fields[4];
extern const pb_field_t machinetalk_Emc_Spindle_Orient_fields[3];
extern const pb_field_t machinetalk_Emc_Spindle_Wait_Orient_Complete_fields[2];
extern const pb_field_t machinetalk_Emc_Tool_Set_Offset_fields[8];
extern const pb_field_t machinetalk_Emc_Traj_Set_Offset_fields[2];
extern const pb_field_t machinetalk_Emc_Tool_Prepare_fields[3];
extern const pb_field_t machinetalk_Emc_Tool_Set_Number_fields[2];
extern const pb_field_t machinetalk_Emc_Traj_Set_Fo_Enable_fields[2];
extern const pb_field_t machinetalk_Emc_Traj_Set_So_Enable_fields[2];
extern const pb_field_t machinetalk_Emc_Traj_Set_Fh_Enable_fields[2];
extern const pb_field_t machinetalk_Emc_Motion_Adaptive_fields[2];
extern const pb_field_t machinetalk_Emc_Operator_Display_fields[3];
extern const pb_field_t machinetalk_Emc_Operator_Text_fields[3];
extern const pb_field_t machinetalk_Emc_Operator_Error_fields[3];
extern const pb_field_t machinetalk_Emc_Motion_Set_Dout_fields[5];
extern const pb_field_t machinetalk_Emc_Motion_Set_Aout_fields[5];
extern const pb_field_t machinetalk_Emc_Aux_Input_Wait_fields[5];
extern const pb_field_t machinetalk_Emc_Exec_Plugin_Ca1l_fields[2];
extern const pb_field_t machinetalk_Emc_Io_Plugin_Call_fields[2];

/* Maximum encoded size of messages (where known) */
#define machinetalk_Emc_Traj_Set_G5x_size        (13 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Traj_Set_G92_size        (6 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Traj_Set_Rotation_size   9
#define machinetalk_Emc_Traj_Linear_Move_size    (58 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Traj_Probe_size          (50 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Traj_Circular_Move_size  (72 + machinetalk_EmcPose_size + machinetalk_PmCartesian_size + machinetalk_PmCartesian_size)
#define machinetalk_Emc_Traj_Rigid_Tap_size      (37 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Traj_Set_Term_Cond_size  16
#define machinetalk_Emc_Traj_Set_Spindlesync_size 12
#define machinetalk_Emc_Traj_Delay_size          9
#define machinetalk_Emc_Spindle_On_size          29
#define machinetalk_Emc_Spindle_Speed_size       29
#define machinetalk_Emc_Spindle_Orient_size      16
#define machinetalk_Emc_Spindle_Wait_Orient_Complete_size 9
#define machinetalk_Emc_Tool_Set_Offset_size     (71 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Traj_Set_Offset_size     (6 + machinetalk_EmcPose_size)
#define machinetalk_Emc_Tool_Prepare_size        23
#define machinetalk_Emc_Tool_Set_Number_size     11
#define machinetalk_Emc_Traj_Set_Fo_Enable_size  2
#define machinetalk_Emc_Traj_Set_So_Enable_size  2
#define machinetalk_Emc_Traj_Set_Fh_Enable_size  2
#define machinetalk_Emc_Motion_Adaptive_size     2
#define machinetalk_Emc_Motion_Set_Dout_size     15
#define machinetalk_Emc_Motion_Set_Aout_size     29
#define machinetalk_Emc_Aux_Input_Wait_size      30

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_100 machinetalk_Emc_Traj_Set_G5x
#define PB_MSG_101 machinetalk_Emc_Traj_Set_G92
#define PB_MSG_102 machinetalk_Emc_Traj_Set_Rotation
#define PB_MSG_103 machinetalk_Emc_Traj_Linear_Move
#define PB_MSG_104 machinetalk_Emc_Traj_Probe
#define PB_MSG_105 machinetalk_Emc_Traj_Circular_Move
#define PB_MSG_106 machinetalk_Emc_Traj_Rigid_Tap
#define PB_MSG_107 machinetalk_Emc_Traj_Set_Term_Cond
#define PB_MSG_108 machinetalk_Emc_Traj_Set_Spindlesync
#define PB_MSG_109 machinetalk_Emc_Traj_Delay
#define PB_MSG_110 machinetalk_Emc_Spindle_On
#define PB_MSG_111 machinetalk_Emc_Spindle_Speed
#define PB_MSG_112 machinetalk_Emc_Spindle_Orient
#define PB_MSG_113 machinetalk_Emc_Spindle_Wait_Orient_Complete
#define PB_MSG_114 machinetalk_Emc_Tool_Set_Offset
#define PB_MSG_115 machinetalk_Emc_Traj_Set_Offset
#define PB_MSG_116 machinetalk_Emc_Tool_Prepare
#define PB_MSG_117 machinetalk_Emc_Tool_Set_Number
#define PB_MSG_118 machinetalk_Emc_Traj_Set_Fo_Enable
#define PB_MSG_119 machinetalk_Emc_Traj_Set_So_Enable
#define PB_MSG_120 machinetalk_Emc_Traj_Set_Fh_Enable
#define PB_MSG_121 machinetalk_Emc_Motion_Adaptive
#define PB_MSG_122 machinetalk_Emc_Operator_Display
#define PB_MSG_123 machinetalk_Emc_Operator_Text
#define PB_MSG_124 machinetalk_Emc_Operator_Error
#define PB_MSG_125 machinetalk_Emc_Motion_Set_Dout
#define PB_MSG_126 machinetalk_Emc_Motion_Set_Aout
#define PB_MSG_127 machinetalk_Emc_Aux_Input_Wait
#define PB_MSG_128 machinetalk_Emc_Exec_Plugin_Ca1l
#define PB_MSG_129 machinetalk_Emc_Io_Plugin_Call

#define CANON_MESSAGES \
	PB_MSG(100,(13 + machinetalk_EmcPose_size),machinetalk_Emc_Traj_Set_G5x) \
	PB_MSG(101,(6 + machinetalk_EmcPose_size),machinetalk_Emc_Traj_Set_G92) \
	PB_MSG(102,9,machinetalk_Emc_Traj_Set_Rotation) \
	PB_MSG(103,(58 + machinetalk_EmcPose_size),machinetalk_Emc_Traj_Linear_Move) \
	PB_MSG(104,(50 + machinetalk_EmcPose_size),machinetalk_Emc_Traj_Probe) \
	PB_MSG(105,(72 + machinetalk_EmcPose_size + machinetalk_PmCartesian_size + machinetalk_PmCartesian_size),machinetalk_Emc_Traj_Circular_Move) \
	PB_MSG(106,(37 + machinetalk_EmcPose_size),machinetalk_Emc_Traj_Rigid_Tap) \
	PB_MSG(107,16,machinetalk_Emc_Traj_Set_Term_Cond) \
	PB_MSG(108,12,machinetalk_Emc_Traj_Set_Spindlesync) \
	PB_MSG(109,9,machinetalk_Emc_Traj_Delay) \
	PB_MSG(110,29,machinetalk_Emc_Spindle_On) \
	PB_MSG(111,29,machinetalk_Emc_Spindle_Speed) \
	PB_MSG(112,16,machinetalk_Emc_Spindle_Orient) \
	PB_MSG(113,9,machinetalk_Emc_Spindle_Wait_Orient_Complete) \
	PB_MSG(114,(71 + machinetalk_EmcPose_size),machinetalk_Emc_Tool_Set_Offset) \
	PB_MSG(115,(6 + machinetalk_EmcPose_size),machinetalk_Emc_Traj_Set_Offset) \
	PB_MSG(116,23,machinetalk_Emc_Tool_Prepare) \
	PB_MSG(117,11,machinetalk_Emc_Tool_Set_Number) \
	PB_MSG(118,2,machinetalk_Emc_Traj_Set_Fo_Enable) \
	PB_MSG(119,2,machinetalk_Emc_Traj_Set_So_Enable) \
	PB_MSG(120,2,machinetalk_Emc_Traj_Set_Fh_Enable) \
	PB_MSG(121,2,machinetalk_Emc_Motion_Adaptive) \
	PB_MSG(122,-1,machinetalk_Emc_Operator_Display) \
	PB_MSG(123,-1,machinetalk_Emc_Operator_Text) \
	PB_MSG(124,-1,machinetalk_Emc_Operator_Error) \
	PB_MSG(125,15,machinetalk_Emc_Motion_Set_Dout) \
	PB_MSG(126,29,machinetalk_Emc_Motion_Set_Aout) \
	PB_MSG(127,30,machinetalk_Emc_Aux_Input_Wait) \
	PB_MSG(128,-1,machinetalk_Emc_Exec_Plugin_Ca1l) \
	PB_MSG(129,-1,machinetalk_Emc_Io_Plugin_Call) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
