/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_CONFIG_NPB_H_INCLUDED
#define PB_CONFIG_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _machinetalk_ApplicationType {
    machinetalk_ApplicationType_QT5_QML = 1,
    machinetalk_ApplicationType_GLADEVCP = 2,
    machinetalk_ApplicationType_JAVASCRIPT = 3
} machinetalk_ApplicationType;

typedef enum _machinetalk_FileContent {
    machinetalk_FileContent_CLEARTEXT = 1,
    machinetalk_FileContent_ZLIB = 2
} machinetalk_FileContent;

/* Struct definitions */
typedef struct _machinetalk_MachineInfo {
    pb_callback_t type;
    pb_callback_t manufacturer;
    pb_callback_t model;
    pb_callback_t variant;
} machinetalk_MachineInfo;

typedef struct _machinetalk_Application {
    pb_callback_t name;
    pb_callback_t description;
    bool has_type;
    machinetalk_ApplicationType type;
    pb_callback_t weburi;
    pb_callback_t file;
} machinetalk_Application;

typedef struct _machinetalk_File {
    pb_callback_t name;
    machinetalk_FileContent encoding;
    pb_callback_t blob;
} machinetalk_File;

typedef struct _machinetalk_StdoutLine {
    int32_t index;
    pb_callback_t line;
} machinetalk_StdoutLine;

typedef struct _machinetalk_Launcher {
    int32_t index;
    pb_callback_t name;
    pb_callback_t description;
    bool has_image;
    machinetalk_File image;
    bool has_info;
    machinetalk_MachineInfo info;
    bool has_running;
    bool running;
    bool has_terminating;
    bool terminating;
    pb_callback_t command;
    bool has_shell;
    bool shell;
    pb_callback_t output;
    bool has_returncode;
    int32_t returncode;
    pb_callback_t workdir;
    bool has_priority;
    uint32_t priority;
} machinetalk_Launcher;

/* Default values for struct fields */

/* Initializer values for message structs */
#define machinetalk_File_init_default            {{{NULL}, NULL}, (machinetalk_FileContent)0, {{NULL}, NULL}}
#define machinetalk_Application_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_ApplicationType)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define machinetalk_StdoutLine_init_default      {0, {{NULL}, NULL}}
#define machinetalk_MachineInfo_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define machinetalk_Launcher_init_default        {0, {{NULL}, NULL}, {{NULL}, NULL}, false, machinetalk_File_init_default, false, machinetalk_MachineInfo_init_default, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0}
#define machinetalk_File_init_zero               {{{NULL}, NULL}, (machinetalk_FileContent)0, {{NULL}, NULL}}
#define machinetalk_Application_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_ApplicationType)0, {{NULL}, NULL}, {{NULL}, NULL}}
#define machinetalk_StdoutLine_init_zero         {0, {{NULL}, NULL}}
#define machinetalk_MachineInfo_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define machinetalk_Launcher_init_zero           {0, {{NULL}, NULL}, {{NULL}, NULL}, false, machinetalk_File_init_zero, false, machinetalk_MachineInfo_init_zero, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_MachineInfo_type_tag         1
#define machinetalk_MachineInfo_manufacturer_tag 2
#define machinetalk_MachineInfo_model_tag        3
#define machinetalk_MachineInfo_variant_tag      4
#define machinetalk_Application_name_tag         1
#define machinetalk_Application_description_tag  2
#define machinetalk_Application_type_tag         3
#define machinetalk_Application_weburi_tag       4
#define machinetalk_Application_file_tag         5
#define machinetalk_File_name_tag                1
#define machinetalk_File_encoding_tag            2
#define machinetalk_File_blob_tag                3
#define machinetalk_StdoutLine_index_tag         1
#define machinetalk_StdoutLine_line_tag          2
#define machinetalk_Launcher_index_tag           1
#define machinetalk_Launcher_name_tag            2
#define machinetalk_Launcher_description_tag     3
#define machinetalk_Launcher_image_tag           4
#define machinetalk_Launcher_info_tag            5
#define machinetalk_Launcher_running_tag         6
#define machinetalk_Launcher_terminating_tag     7
#define machinetalk_Launcher_command_tag         8
#define machinetalk_Launcher_shell_tag           9
#define machinetalk_Launcher_output_tag          10
#define machinetalk_Launcher_returncode_tag      11
#define machinetalk_Launcher_workdir_tag         12
#define machinetalk_Launcher_priority_tag        13

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_File_fields[4];
extern const pb_field_t machinetalk_Application_fields[6];
extern const pb_field_t machinetalk_StdoutLine_fields[3];
extern const pb_field_t machinetalk_MachineInfo_fields[5];
extern const pb_field_t machinetalk_Launcher_fields[14];

/* Maximum encoded size of messages (where known) */

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_200 machinetalk_File
#define PB_MSG_201 machinetalk_Application
#define PB_MSG_202 machinetalk_StdoutLine
#define PB_MSG_203 machinetalk_MachineInfo
#define PB_MSG_204 machinetalk_Launcher

#define CONFIG_MESSAGES \
	PB_MSG(200,-1,machinetalk_File) \
	PB_MSG(201,-1,machinetalk_Application) \
	PB_MSG(202,-1,machinetalk_StdoutLine) \
	PB_MSG(203,-1,machinetalk_MachineInfo) \
	PB_MSG(204,-1,machinetalk_Launcher) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
