/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_JPLAN_NPB_H_INCLUDED
#define PB_JPLAN_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _pb_JplanJoint {
    bool has_pos_cmd;
    double pos_cmd;
    bool has_max_vel;
    double max_vel;
    bool has_max_acc;
    double max_acc;
    bool has_enable;
    bool enable;
} pb_JplanJoint;

typedef struct _pb_JplanCommand {
    pb_size_t joint_count;
    pb_JplanJoint joint[10];
} pb_JplanCommand;

/* Default values for struct fields */

/* Initializer values for message structs */
#define pb_JplanJoint_init_default               {false, 0, false, 0, false, 0, false, 0}
#define pb_JplanCommand_init_default             {0, {pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default, pb_JplanJoint_init_default}}
#define pb_JplanJoint_init_zero                  {false, 0, false, 0, false, 0, false, 0}
#define pb_JplanCommand_init_zero                {0, {pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero, pb_JplanJoint_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define pb_JplanJoint_pos_cmd_tag                1
#define pb_JplanJoint_max_vel_tag                2
#define pb_JplanJoint_max_acc_tag                3
#define pb_JplanJoint_enable_tag                 4
#define pb_JplanCommand_joint_tag                2

/* Struct field encoding specification for nanopb */
extern const pb_field_t pb_JplanJoint_fields[5];
extern const pb_field_t pb_JplanCommand_fields[2];

/* Maximum encoded size of messages (where known) */
#define pb_JplanJoint_size                       29
#define pb_JplanCommand_size                     310

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_352 pb_JplanJoint
#define PB_MSG_354 pb_JplanCommand

#define JPLAN_MESSAGES \
	PB_MSG(352,29,pb_JplanJoint) \
	PB_MSG(354,310,pb_JplanCommand) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
