// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/log.proto

#ifndef PROTOBUF_machinetalk_2fprotobuf_2flog_2eproto__INCLUDED
#define PROTOBUF_machinetalk_2fprotobuf_2flog_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "machinetalk/protobuf/nanopb.pb.h"
#include "machinetalk/protobuf/types.pb.h"
// @@protoc_insertion_point(includes)

namespace machinetalk {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_machinetalk_2fprotobuf_2flog_2eproto();
void protobuf_AssignDesc_machinetalk_2fprotobuf_2flog_2eproto();
void protobuf_ShutdownFile_machinetalk_2fprotobuf_2flog_2eproto();

class LogMessage;

// ===================================================================

class LogMessage : public ::google::protobuf::Message {
 public:
  LogMessage();
  virtual ~LogMessage();

  LogMessage(const LogMessage& from);

  inline LogMessage& operator=(const LogMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogMessage& default_instance();

  void Swap(LogMessage* other);

  // implements Message ----------------------------------------------

  LogMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogMessage& from);
  void MergeFrom(const LogMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .machinetalk.MsgOrigin origin = 10;
  inline bool has_origin() const;
  inline void clear_origin();
  static const int kOriginFieldNumber = 10;
  inline ::machinetalk::MsgOrigin origin() const;
  inline void set_origin(::machinetalk::MsgOrigin value);

  // required int32 pid = 20;
  inline bool has_pid() const;
  inline void clear_pid();
  static const int kPidFieldNumber = 20;
  inline ::google::protobuf::int32 pid() const;
  inline void set_pid(::google::protobuf::int32 value);

  // required .machinetalk.MsgLevel level = 30;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 30;
  inline ::machinetalk::MsgLevel level() const;
  inline void set_level(::machinetalk::MsgLevel value);

  // required string tag = 40;
  inline bool has_tag() const;
  inline void clear_tag();
  static const int kTagFieldNumber = 40;
  inline const ::std::string& tag() const;
  inline void set_tag(const ::std::string& value);
  inline void set_tag(const char* value);
  inline void set_tag(const char* value, size_t size);
  inline ::std::string* mutable_tag();
  inline ::std::string* release_tag();
  inline void set_allocated_tag(::std::string* tag);

  // required string text = 50;
  inline bool has_text() const;
  inline void clear_text();
  static const int kTextFieldNumber = 50;
  inline const ::std::string& text() const;
  inline void set_text(const ::std::string& value);
  inline void set_text(const char* value);
  inline void set_text(const char* value, size_t size);
  inline ::std::string* mutable_text();
  inline ::std::string* release_text();
  inline void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:machinetalk.LogMessage)
 private:
  inline void set_has_origin();
  inline void clear_has_origin();
  inline void set_has_pid();
  inline void clear_has_pid();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_tag();
  inline void clear_has_tag();
  inline void set_has_text();
  inline void clear_has_text();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int origin_;
  ::google::protobuf::int32 pid_;
  ::std::string* tag_;
  ::std::string* text_;
  int level_;
  friend void  protobuf_AddDesc_machinetalk_2fprotobuf_2flog_2eproto();
  friend void protobuf_AssignDesc_machinetalk_2fprotobuf_2flog_2eproto();
  friend void protobuf_ShutdownFile_machinetalk_2fprotobuf_2flog_2eproto();

  void InitAsDefaultInstance();
  static LogMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// LogMessage

// required .machinetalk.MsgOrigin origin = 10;
inline bool LogMessage::has_origin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogMessage::set_has_origin() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogMessage::clear_has_origin() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogMessage::clear_origin() {
  origin_ = 0;
  clear_has_origin();
}
inline ::machinetalk::MsgOrigin LogMessage::origin() const {
  // @@protoc_insertion_point(field_get:machinetalk.LogMessage.origin)
  return static_cast< ::machinetalk::MsgOrigin >(origin_);
}
inline void LogMessage::set_origin(::machinetalk::MsgOrigin value) {
  assert(::machinetalk::MsgOrigin_IsValid(value));
  set_has_origin();
  origin_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.LogMessage.origin)
}

// required int32 pid = 20;
inline bool LogMessage::has_pid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogMessage::set_has_pid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogMessage::clear_has_pid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogMessage::clear_pid() {
  pid_ = 0;
  clear_has_pid();
}
inline ::google::protobuf::int32 LogMessage::pid() const {
  // @@protoc_insertion_point(field_get:machinetalk.LogMessage.pid)
  return pid_;
}
inline void LogMessage::set_pid(::google::protobuf::int32 value) {
  set_has_pid();
  pid_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.LogMessage.pid)
}

// required .machinetalk.MsgLevel level = 30;
inline bool LogMessage::has_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LogMessage::set_has_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LogMessage::clear_has_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LogMessage::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::machinetalk::MsgLevel LogMessage::level() const {
  // @@protoc_insertion_point(field_get:machinetalk.LogMessage.level)
  return static_cast< ::machinetalk::MsgLevel >(level_);
}
inline void LogMessage::set_level(::machinetalk::MsgLevel value) {
  assert(::machinetalk::MsgLevel_IsValid(value));
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.LogMessage.level)
}

// required string tag = 40;
inline bool LogMessage::has_tag() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LogMessage::set_has_tag() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LogMessage::clear_has_tag() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LogMessage::clear_tag() {
  if (tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tag_->clear();
  }
  clear_has_tag();
}
inline const ::std::string& LogMessage::tag() const {
  // @@protoc_insertion_point(field_get:machinetalk.LogMessage.tag)
  return *tag_;
}
inline void LogMessage::set_tag(const ::std::string& value) {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tag_ = new ::std::string;
  }
  tag_->assign(value);
  // @@protoc_insertion_point(field_set:machinetalk.LogMessage.tag)
}
inline void LogMessage::set_tag(const char* value) {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tag_ = new ::std::string;
  }
  tag_->assign(value);
  // @@protoc_insertion_point(field_set_char:machinetalk.LogMessage.tag)
}
inline void LogMessage::set_tag(const char* value, size_t size) {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tag_ = new ::std::string;
  }
  tag_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:machinetalk.LogMessage.tag)
}
inline ::std::string* LogMessage::mutable_tag() {
  set_has_tag();
  if (tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tag_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:machinetalk.LogMessage.tag)
  return tag_;
}
inline ::std::string* LogMessage::release_tag() {
  clear_has_tag();
  if (tag_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = tag_;
    tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LogMessage::set_allocated_tag(::std::string* tag) {
  if (tag_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete tag_;
  }
  if (tag) {
    set_has_tag();
    tag_ = tag;
  } else {
    clear_has_tag();
    tag_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:machinetalk.LogMessage.tag)
}

// required string text = 50;
inline bool LogMessage::has_text() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LogMessage::set_has_text() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LogMessage::clear_has_text() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LogMessage::clear_text() {
  if (text_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    text_->clear();
  }
  clear_has_text();
}
inline const ::std::string& LogMessage::text() const {
  // @@protoc_insertion_point(field_get:machinetalk.LogMessage.text)
  return *text_;
}
inline void LogMessage::set_text(const ::std::string& value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    text_ = new ::std::string;
  }
  text_->assign(value);
  // @@protoc_insertion_point(field_set:machinetalk.LogMessage.text)
}
inline void LogMessage::set_text(const char* value) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    text_ = new ::std::string;
  }
  text_->assign(value);
  // @@protoc_insertion_point(field_set_char:machinetalk.LogMessage.text)
}
inline void LogMessage::set_text(const char* value, size_t size) {
  set_has_text();
  if (text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    text_ = new ::std::string;
  }
  text_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:machinetalk.LogMessage.text)
}
inline ::std::string* LogMessage::mutable_text() {
  set_has_text();
  if (text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    text_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:machinetalk.LogMessage.text)
  return text_;
}
inline ::std::string* LogMessage::release_text() {
  clear_has_text();
  if (text_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = text_;
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LogMessage::set_allocated_text(::std::string* text) {
  if (text_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete text_;
  }
  if (text) {
    set_has_text();
    text_ = text;
  } else {
    clear_has_text();
    text_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:machinetalk.LogMessage.text)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace machinetalk

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_machinetalk_2fprotobuf_2flog_2eproto__INCLUDED
