/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_OBJECT_NPB_H_INCLUDED
#define PB_OBJECT_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#include "machinetalk/protobuf/types.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _machinetalk_Component {
    pb_callback_t name;
    bool has_ninst;
    uint32_t ninst;
    bool has_comp_id;
    int32_t comp_id;
    bool has_type;
    uint32_t type;
    bool has_state;
    uint32_t state;
    bool has_last_update;
    uint32_t last_update;
    bool has_last_bound;
    uint32_t last_bound;
    bool has_last_unbound;
    uint32_t last_unbound;
    bool has_pid;
    uint32_t pid;
    pb_callback_t args;
    bool has_timer;
    int32_t timer;
    bool has_userarg1;
    int32_t userarg1;
    bool has_userarg2;
    int32_t userarg2;
    pb_callback_t pin;
    pb_callback_t param;
    bool has_no_create;
    bool no_create;
    pb_callback_t funct;
} machinetalk_Component;

typedef struct _machinetalk_Function {
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_owner_id;
    uint32_t owner_id;
    bool has_users;
    uint32_t users;
    bool has_runtime;
    uint32_t runtime;
    bool has_maxtime;
    uint32_t maxtime;
    bool has_reentrant;
    bool reentrant;
    bool has_type;
    machinetalk_HalFunctType type;
    bool has_maxtime_increased;
    bool maxtime_increased;
} machinetalk_Function;

typedef struct _machinetalk_Group {
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_userarg1;
    int32_t userarg1;
    bool has_userarg2;
    int32_t userarg2;
    bool has_refcount;
    int32_t refcount;
    pb_callback_t member;
} machinetalk_Group;

typedef struct _machinetalk_Inst {
    pb_callback_t name;
    bool has_comp_id;
    int32_t comp_id;
    bool has_inst_id;
    uint32_t inst_id;
    bool has_inst_size;
    uint32_t inst_size;
    bool has_vtable;
    uint64_t vtable;
    pb_callback_t pin;
    pb_callback_t param;
    pb_callback_t funct;
} machinetalk_Inst;

typedef struct _machinetalk_Instance {
    pb_callback_t name;
    bool has_id;
    int32_t id;
} machinetalk_Instance;

typedef struct _machinetalk_Param {
    bool has_type;
    machinetalk_ValueType type;
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_halbit;
    bool halbit;
    bool has_halfloat;
    double halfloat;
    bool has_hals32;
    int32_t hals32;
    bool has_halu32;
    uint32_t halu32;
    pb_callback_t strval;
    pb_callback_t blob;
    bool has_dir;
    machinetalk_HalParamDirection dir;
    pb_callback_t oldname;
    bool has_owner;
    int32_t owner;
    bool has_runtime;
    int32_t runtime;
    bool has_maytime;
    int32_t maytime;
} machinetalk_Param;

typedef struct _machinetalk_Pin {
    bool has_type;
    machinetalk_ValueType type;
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_dir;
    machinetalk_HalPinDirection dir;
    bool has_halbit;
    bool halbit;
    bool has_halfloat;
    double halfloat;
    bool has_hals32;
    int32_t hals32;
    bool has_halu32;
    uint32_t halu32;
    bool has_owner;
    int32_t owner;
    bool has_linked;
    bool linked;
    pb_callback_t oldname;
    bool has_epsilon;
    double epsilon;
    bool has_flags;
    uint32_t flags;
} machinetalk_Pin;

typedef struct _machinetalk_ProtocolParameters {
    bool has_keepalive_timer;
    int32_t keepalive_timer;
    bool has_group_timer;
    int32_t group_timer;
    bool has_rcomp_timer;
    int32_t rcomp_timer;
} machinetalk_ProtocolParameters;

typedef struct _machinetalk_Ring {
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_owner;
    int32_t owner;
    bool has_stream;
    bool stream;
    bool has_wmutex;
    bool wmutex;
    bool has_rmutex;
    bool rmutex;
    bool has_rtapi_shm;
    bool rtapi_shm;
    bool has_reader;
    int32_t reader;
    bool has_writer;
    int32_t writer;
    bool has_total_size;
    int32_t total_size;
    bool has_scratchpad;
    int32_t scratchpad;
    bool has_ring_shmkey;
    int32_t ring_shmkey;
    bool has_encodings;
    uint32_t encodings;
} machinetalk_Ring;

typedef struct _machinetalk_ServiceAnnouncement {
    machinetalk_ServiceType stype;
    uint32_t version;
    uint32_t instance;
    pb_callback_t uri;
    pb_callback_t description;
    machinetalk_ServiceAPI api;
} machinetalk_ServiceAnnouncement;

typedef struct _machinetalk_Signal {
    bool has_type;
    machinetalk_ValueType type;
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_halbit;
    bool halbit;
    bool has_halfloat;
    double halfloat;
    bool has_hals32;
    int32_t hals32;
    bool has_halu32;
    uint32_t halu32;
    pb_callback_t strval;
    pb_callback_t blob;
    bool has_readers;
    uint32_t readers;
    bool has_writers;
    uint32_t writers;
    bool has_bidirs;
    uint32_t bidirs;
} machinetalk_Signal;

typedef struct _machinetalk_Thread {
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_uses_fp;
    bool uses_fp;
    bool has_period;
    uint32_t period;
    bool has_priority;
    int32_t priority;
    bool has_task_id;
    uint32_t task_id;
    bool has_cpu_id;
    uint32_t cpu_id;
    pb_callback_t function;
} machinetalk_Thread;

typedef struct _machinetalk_Vtable {
    pb_callback_t name;
    bool has_handle;
    uint32_t handle;
    bool has_owner_id;
    int32_t owner_id;
    bool has_context;
    uint32_t context;
    bool has_refcount;
    int32_t refcount;
    bool has_version;
    int32_t version;
    bool has_vtable;
    uint64_t vtable;
} machinetalk_Vtable;

typedef struct _machinetalk_Member {
    bool has_mtype;
    machinetalk_ObjectType mtype;
    bool has_userarg1;
    int32_t userarg1;
    bool has_epsilon;
    double epsilon;
    bool has_signal;
    machinetalk_Signal signal;
    pb_callback_t groupname;
    bool has_handle;
    uint32_t handle;
    bool has_pin;
    machinetalk_Pin pin;
    bool has_param;
    machinetalk_Param param;
} machinetalk_Member;

typedef struct _machinetalk_Originator {
    bool has_origin;
    machinetalk_OriginType origin;
    bool has_detail;
    machinetalk_OriginDetail detail;
    pb_callback_t name;
    bool has_id;
    int32_t id;
    bool has_instance;
    machinetalk_Instance instance;
} machinetalk_Originator;

typedef struct _machinetalk_AnError {
    int32_t error_code;
    bool has_severity;
    machinetalk_Severity severity;
    pb_callback_t error_text;
    bool has_origin;
    machinetalk_Originator origin;
} machinetalk_AnError;

/* Default values for struct fields */
extern const uint32_t machinetalk_ServiceAnnouncement_version_default;
extern const uint32_t machinetalk_ServiceAnnouncement_instance_default;

/* Initializer values for message structs */
#define machinetalk_Instance_init_default        {{{NULL}, NULL}, false, 0}
#define machinetalk_ServiceAnnouncement_init_default {(machinetalk_ServiceType)0, 0u, 0u, {{NULL}, NULL}, {{NULL}, NULL}, (machinetalk_ServiceAPI)0}
#define machinetalk_Originator_init_default      {false, (machinetalk_OriginType)0, false, (machinetalk_OriginDetail)0, {{NULL}, NULL}, false, 0, false, machinetalk_Instance_init_default}
#define machinetalk_AnError_init_default         {0, false, (machinetalk_Severity)0, {{NULL}, NULL}, false, machinetalk_Originator_init_default}
#define machinetalk_Pin_init_default             {false, (machinetalk_ValueType)0, {{NULL}, NULL}, false, 0, false, (machinetalk_HalPinDirection)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define machinetalk_Signal_init_default          {false, (machinetalk_ValueType)0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define machinetalk_Param_init_default           {false, (machinetalk_ValueType)0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_HalParamDirection)0, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define machinetalk_Function_init_default        {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, (machinetalk_HalFunctType)0, false, 0}
#define machinetalk_Thread_init_default          {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define machinetalk_Component_init_default       {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define machinetalk_Ring_init_default            {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_Member_init_default          {false, (machinetalk_ObjectType)0, false, 0, false, 0, false, machinetalk_Signal_init_default, {{NULL}, NULL}, false, 0, false, machinetalk_Pin_init_default, false, machinetalk_Param_init_default}
#define machinetalk_Group_init_default           {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define machinetalk_ProtocolParameters_init_default {false, 0, false, 0, false, 0}
#define machinetalk_Vtable_init_default          {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_Inst_init_default            {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define machinetalk_Instance_init_zero           {{{NULL}, NULL}, false, 0}
#define machinetalk_ServiceAnnouncement_init_zero {(machinetalk_ServiceType)0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, (machinetalk_ServiceAPI)0}
#define machinetalk_Originator_init_zero         {false, (machinetalk_OriginType)0, false, (machinetalk_OriginDetail)0, {{NULL}, NULL}, false, 0, false, machinetalk_Instance_init_zero}
#define machinetalk_AnError_init_zero            {0, false, (machinetalk_Severity)0, {{NULL}, NULL}, false, machinetalk_Originator_init_zero}
#define machinetalk_Pin_init_zero                {false, (machinetalk_ValueType)0, {{NULL}, NULL}, false, 0, false, (machinetalk_HalPinDirection)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0}
#define machinetalk_Signal_init_zero             {false, (machinetalk_ValueType)0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define machinetalk_Param_init_zero              {false, (machinetalk_ValueType)0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_HalParamDirection)0, {{NULL}, NULL}, false, 0, false, 0, false, 0}
#define machinetalk_Function_init_zero           {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, (machinetalk_HalFunctType)0, false, 0}
#define machinetalk_Thread_init_zero             {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define machinetalk_Component_init_zero          {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define machinetalk_Ring_init_zero               {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_Member_init_zero             {false, (machinetalk_ObjectType)0, false, 0, false, 0, false, machinetalk_Signal_init_zero, {{NULL}, NULL}, false, 0, false, machinetalk_Pin_init_zero, false, machinetalk_Param_init_zero}
#define machinetalk_Group_init_zero              {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define machinetalk_ProtocolParameters_init_zero {false, 0, false, 0, false, 0}
#define machinetalk_Vtable_init_zero             {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_Inst_init_zero               {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_Component_name_tag           1
#define machinetalk_Component_ninst_tag          2
#define machinetalk_Component_comp_id_tag        4
#define machinetalk_Component_type_tag           5
#define machinetalk_Component_state_tag          6
#define machinetalk_Component_last_update_tag    7
#define machinetalk_Component_last_bound_tag     8
#define machinetalk_Component_last_unbound_tag   9
#define machinetalk_Component_pid_tag            10
#define machinetalk_Component_args_tag           11
#define machinetalk_Component_timer_tag          12
#define machinetalk_Component_userarg1_tag       14
#define machinetalk_Component_userarg2_tag       15
#define machinetalk_Component_pin_tag            16
#define machinetalk_Component_param_tag          17
#define machinetalk_Component_funct_tag          19
#define machinetalk_Component_no_create_tag      18
#define machinetalk_Function_name_tag            1
#define machinetalk_Function_handle_tag          2
#define machinetalk_Function_owner_id_tag        3
#define machinetalk_Function_users_tag           4
#define machinetalk_Function_runtime_tag         5
#define machinetalk_Function_maxtime_tag         6
#define machinetalk_Function_reentrant_tag       7
#define machinetalk_Function_type_tag            8
#define machinetalk_Function_maxtime_increased_tag 9
#define machinetalk_Group_name_tag               1
#define machinetalk_Group_handle_tag             2
#define machinetalk_Group_userarg1_tag           4
#define machinetalk_Group_userarg2_tag           5
#define machinetalk_Group_refcount_tag           6
#define machinetalk_Group_member_tag             7
#define machinetalk_Inst_name_tag                1
#define machinetalk_Inst_comp_id_tag             2
#define machinetalk_Inst_inst_id_tag             3
#define machinetalk_Inst_inst_size_tag           4
#define machinetalk_Inst_vtable_tag              5
#define machinetalk_Inst_pin_tag                 16
#define machinetalk_Inst_param_tag               17
#define machinetalk_Inst_funct_tag               19
#define machinetalk_Instance_name_tag            1
#define machinetalk_Instance_id_tag              2
#define machinetalk_Param_type_tag               1
#define machinetalk_Param_name_tag               2
#define machinetalk_Param_handle_tag             3
#define machinetalk_Param_halbit_tag             5
#define machinetalk_Param_halfloat_tag           6
#define machinetalk_Param_hals32_tag             7
#define machinetalk_Param_halu32_tag             8
#define machinetalk_Param_strval_tag             9
#define machinetalk_Param_blob_tag               10
#define machinetalk_Param_dir_tag                11
#define machinetalk_Param_oldname_tag            12
#define machinetalk_Param_owner_tag              13
#define machinetalk_Param_runtime_tag            14
#define machinetalk_Param_maytime_tag            15
#define machinetalk_Pin_type_tag                 1
#define machinetalk_Pin_name_tag                 2
#define machinetalk_Pin_handle_tag               3
#define machinetalk_Pin_dir_tag                  4
#define machinetalk_Pin_halbit_tag               5
#define machinetalk_Pin_halfloat_tag             6
#define machinetalk_Pin_hals32_tag               7
#define machinetalk_Pin_halu32_tag               8
#define machinetalk_Pin_owner_tag                9
#define machinetalk_Pin_linked_tag               10
#define machinetalk_Pin_oldname_tag              11
#define machinetalk_Pin_epsilon_tag              12
#define machinetalk_Pin_flags_tag                13
#define machinetalk_ProtocolParameters_keepalive_timer_tag 1
#define machinetalk_ProtocolParameters_group_timer_tag 2
#define machinetalk_ProtocolParameters_rcomp_timer_tag 3
#define machinetalk_Ring_name_tag                1
#define machinetalk_Ring_handle_tag              2
#define machinetalk_Ring_owner_tag               3
#define machinetalk_Ring_stream_tag              4
#define machinetalk_Ring_wmutex_tag              5
#define machinetalk_Ring_rmutex_tag              6
#define machinetalk_Ring_rtapi_shm_tag           7
#define machinetalk_Ring_reader_tag              8
#define machinetalk_Ring_writer_tag              9
#define machinetalk_Ring_total_size_tag          10
#define machinetalk_Ring_scratchpad_tag          11
#define machinetalk_Ring_ring_shmkey_tag         12
#define machinetalk_Ring_encodings_tag           13
#define machinetalk_ServiceAnnouncement_stype_tag 1
#define machinetalk_ServiceAnnouncement_version_tag 2
#define machinetalk_ServiceAnnouncement_instance_tag 3
#define machinetalk_ServiceAnnouncement_api_tag  8
#define machinetalk_ServiceAnnouncement_uri_tag  6
#define machinetalk_ServiceAnnouncement_description_tag 7
#define machinetalk_Signal_type_tag              1
#define machinetalk_Signal_name_tag              2
#define machinetalk_Signal_handle_tag            3
#define machinetalk_Signal_halbit_tag            5
#define machinetalk_Signal_halfloat_tag          6
#define machinetalk_Signal_hals32_tag            7
#define machinetalk_Signal_halu32_tag            8
#define machinetalk_Signal_strval_tag            9
#define machinetalk_Signal_blob_tag              10
#define machinetalk_Signal_readers_tag           11
#define machinetalk_Signal_writers_tag           12
#define machinetalk_Signal_bidirs_tag            13
#define machinetalk_Thread_name_tag              1
#define machinetalk_Thread_handle_tag            2
#define machinetalk_Thread_uses_fp_tag           3
#define machinetalk_Thread_period_tag            4
#define machinetalk_Thread_priority_tag          5
#define machinetalk_Thread_task_id_tag           6
#define machinetalk_Thread_cpu_id_tag            7
#define machinetalk_Thread_function_tag          8
#define machinetalk_Vtable_name_tag              1
#define machinetalk_Vtable_handle_tag            2
#define machinetalk_Vtable_owner_id_tag          3
#define machinetalk_Vtable_context_tag           5
#define machinetalk_Vtable_refcount_tag          6
#define machinetalk_Vtable_version_tag           7
#define machinetalk_Vtable_vtable_tag            8
#define machinetalk_Member_mtype_tag             1
#define machinetalk_Member_userarg1_tag          2
#define machinetalk_Member_epsilon_tag           3
#define machinetalk_Member_signal_tag            4
#define machinetalk_Member_groupname_tag         5
#define machinetalk_Member_handle_tag            6
#define machinetalk_Member_pin_tag               7
#define machinetalk_Member_param_tag             8
#define machinetalk_Originator_origin_tag        1
#define machinetalk_Originator_detail_tag        2
#define machinetalk_Originator_name_tag          3
#define machinetalk_Originator_id_tag            4
#define machinetalk_Originator_instance_tag      5
#define machinetalk_AnError_error_code_tag       1
#define machinetalk_AnError_severity_tag         2
#define machinetalk_AnError_error_text_tag       3
#define machinetalk_AnError_origin_tag           4

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_Instance_fields[3];
extern const pb_field_t machinetalk_ServiceAnnouncement_fields[7];
extern const pb_field_t machinetalk_Originator_fields[6];
extern const pb_field_t machinetalk_AnError_fields[5];
extern const pb_field_t machinetalk_Pin_fields[14];
extern const pb_field_t machinetalk_Signal_fields[13];
extern const pb_field_t machinetalk_Param_fields[15];
extern const pb_field_t machinetalk_Function_fields[10];
extern const pb_field_t machinetalk_Thread_fields[9];
extern const pb_field_t machinetalk_Component_fields[18];
extern const pb_field_t machinetalk_Ring_fields[14];
extern const pb_field_t machinetalk_Member_fields[9];
extern const pb_field_t machinetalk_Group_fields[7];
extern const pb_field_t machinetalk_ProtocolParameters_fields[4];
extern const pb_field_t machinetalk_Vtable_fields[8];
extern const pb_field_t machinetalk_Inst_fields[9];

/* Maximum encoded size of messages (where known) */
#define machinetalk_ProtocolParameters_size      15

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_700 machinetalk_Instance
#define PB_MSG_701 machinetalk_ServiceAnnouncement
#define PB_MSG_702 machinetalk_Originator
#define PB_MSG_703 machinetalk_AnError
#define PB_MSG_704 machinetalk_Pin
#define PB_MSG_705 machinetalk_Signal
#define PB_MSG_706 machinetalk_Param
#define PB_MSG_707 machinetalk_Function
#define PB_MSG_708 machinetalk_Thread
#define PB_MSG_709 machinetalk_Component
#define PB_MSG_710 machinetalk_Ring
#define PB_MSG_711 machinetalk_Member
#define PB_MSG_712 machinetalk_Group
#define PB_MSG_713 machinetalk_ProtocolParameters
#define PB_MSG_714 machinetalk_Vtable
#define PB_MSG_715 machinetalk_Inst

#define OBJECT_MESSAGES \
	PB_MSG(700,-1,machinetalk_Instance) \
	PB_MSG(701,-1,machinetalk_ServiceAnnouncement) \
	PB_MSG(702,-1,machinetalk_Originator) \
	PB_MSG(703,-1,machinetalk_AnError) \
	PB_MSG(704,-1,machinetalk_Pin) \
	PB_MSG(705,-1,machinetalk_Signal) \
	PB_MSG(706,-1,machinetalk_Param) \
	PB_MSG(707,-1,machinetalk_Function) \
	PB_MSG(708,-1,machinetalk_Thread) \
	PB_MSG(709,-1,machinetalk_Component) \
	PB_MSG(710,-1,machinetalk_Ring) \
	PB_MSG(711,-1,machinetalk_Member) \
	PB_MSG(712,-1,machinetalk_Group) \
	PB_MSG(713,15,machinetalk_ProtocolParameters) \
	PB_MSG(714,-1,machinetalk_Vtable) \
	PB_MSG(715,-1,machinetalk_Inst) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
