/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_PREVIEW_NPB_H_INCLUDED
#define PB_PREVIEW_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _machinetalk_KinematicsType {
    machinetalk_KinematicsType_KT_JOINT = 1,
    machinetalk_KinematicsType_KT_TRIVKINS = 2,
    machinetalk_KinematicsType_KT_DELTA = 3
} machinetalk_KinematicsType;

typedef enum _machinetalk_PreviewOpType {
    machinetalk_PreviewOpType_PV_STRAIGHT_PROBE = 1,
    machinetalk_PreviewOpType_PV_RIGID_TAP = 2,
    machinetalk_PreviewOpType_PV_STRAIGHT_FEED = 3,
    machinetalk_PreviewOpType_PV_ARC_FEED = 4,
    machinetalk_PreviewOpType_PV_STRAIGHT_TRAVERSE = 5,
    machinetalk_PreviewOpType_PV_SET_G5X_OFFSET = 6,
    machinetalk_PreviewOpType_PV_SET_G92_OFFSET = 7,
    machinetalk_PreviewOpType_PV_SET_XY_ROTATION = 8,
    machinetalk_PreviewOpType_PV_SELECT_PLANE = 9,
    machinetalk_PreviewOpType_PV_SET_TRAVERSE_RATE = 10,
    machinetalk_PreviewOpType_PV_SET_FEED_RATE = 11,
    machinetalk_PreviewOpType_PV_CHANGE_TOOL = 12,
    machinetalk_PreviewOpType_PV_CHANGE_TOOL_NUMBER = 13,
    machinetalk_PreviewOpType_PV_DWELL = 14,
    machinetalk_PreviewOpType_PV_MESSAGE = 15,
    machinetalk_PreviewOpType_PV_COMMENT = 16,
    machinetalk_PreviewOpType_PV_USE_TOOL_OFFSET = 17,
    machinetalk_PreviewOpType_PV_SET_PARAMS = 18,
    machinetalk_PreviewOpType_PV_SET_FEED_MODE = 19,
    machinetalk_PreviewOpType_PV_SOURCE_CONTEXT = 20,
    machinetalk_PreviewOpType_PV_PREVIEW_START = 21,
    machinetalk_PreviewOpType_PV_PREVIEW_END = 22
} machinetalk_PreviewOpType;

typedef enum _machinetalk_SourceType {
    machinetalk_SourceType_ST_NGC_FILE = 1,
    machinetalk_SourceType_ST_NGC_STRING = 2,
    machinetalk_SourceType_ST_PYTHON_METHOD = 3
} machinetalk_SourceType;

/* Struct definitions */
typedef struct _machinetalk_Position {
    bool has_x;
    double x;
    bool has_y;
    double y;
    bool has_z;
    double z;
    bool has_a;
    double a;
    bool has_b;
    double b;
    bool has_c;
    double c;
    bool has_u;
    double u;
    bool has_v;
    double v;
    bool has_w;
    double w;
} machinetalk_Position;

typedef struct _machinetalk_Preview {
    machinetalk_PreviewOpType type;
    bool has_line_number;
    int32_t line_number;
    bool has_pos;
    machinetalk_Position pos;
    bool has_first_end;
    double first_end;
    bool has_second_end;
    double second_end;
    bool has_first_axis;
    double first_axis;
    bool has_second_axis;
    double second_axis;
    bool has_rotation;
    int32_t rotation;
    bool has_axis_end_point;
    double axis_end_point;
    bool has_xy_rotation;
    double xy_rotation;
    bool has_plane;
    int32_t plane;
    bool has_rate;
    double rate;
    bool has_feed_mode;
    int32_t feed_mode;
    bool has_time;
    double time;
    pb_callback_t text;
    bool has_angular_units;
    double angular_units;
    bool has_length_units;
    double length_units;
    bool has_probetype;
    int32_t probetype;
    bool has_kins;
    machinetalk_KinematicsType kins;
    bool has_axismask;
    int32_t axismask;
    bool has_g5_index;
    int32_t g5_index;
    bool has_pocket;
    int32_t pocket;
    bool has_stype;
    machinetalk_SourceType stype;
    pb_callback_t filename;
    pb_callback_t cmdstring;
    bool has_call_level;
    int32_t call_level;
} machinetalk_Preview;

/* Default values for struct fields */
extern const machinetalk_KinematicsType machinetalk_Preview_kins_default;

/* Initializer values for message structs */
#define machinetalk_Position_init_default        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_Preview_init_default         {(machinetalk_PreviewOpType)0, false, 0, false, machinetalk_Position_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, machinetalk_KinematicsType_KT_JOINT, false, 0, false, 0, false, 0, false, (machinetalk_SourceType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define machinetalk_Position_init_zero           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_Preview_init_zero            {(machinetalk_PreviewOpType)0, false, 0, false, machinetalk_Position_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, (machinetalk_KinematicsType)0, false, 0, false, 0, false, 0, false, (machinetalk_SourceType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_Position_x_tag               3
#define machinetalk_Position_y_tag               4
#define machinetalk_Position_z_tag               5
#define machinetalk_Position_a_tag               6
#define machinetalk_Position_b_tag               7
#define machinetalk_Position_c_tag               8
#define machinetalk_Position_u_tag               9
#define machinetalk_Position_v_tag               10
#define machinetalk_Position_w_tag               11
#define machinetalk_Preview_type_tag             1
#define machinetalk_Preview_line_number_tag      2
#define machinetalk_Preview_pos_tag              3
#define machinetalk_Preview_first_end_tag        4
#define machinetalk_Preview_second_end_tag       5
#define machinetalk_Preview_first_axis_tag       6
#define machinetalk_Preview_second_axis_tag      7
#define machinetalk_Preview_rotation_tag         8
#define machinetalk_Preview_axis_end_point_tag   9
#define machinetalk_Preview_xy_rotation_tag      10
#define machinetalk_Preview_plane_tag            11
#define machinetalk_Preview_rate_tag             12
#define machinetalk_Preview_feed_mode_tag        13
#define machinetalk_Preview_time_tag             14
#define machinetalk_Preview_text_tag             15
#define machinetalk_Preview_angular_units_tag    101
#define machinetalk_Preview_length_units_tag     102
#define machinetalk_Preview_probetype_tag        103
#define machinetalk_Preview_kins_tag             104
#define machinetalk_Preview_axismask_tag         105
#define machinetalk_Preview_g5_index_tag         106
#define machinetalk_Preview_pocket_tag           107
#define machinetalk_Preview_stype_tag            110
#define machinetalk_Preview_filename_tag         111
#define machinetalk_Preview_cmdstring_tag        112
#define machinetalk_Preview_call_level_tag       113

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_Position_fields[10];
extern const pb_field_t machinetalk_Preview_fields[27];

/* Maximum encoded size of messages (where known) */
#define machinetalk_Position_size                81

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_800 machinetalk_Position
#define PB_MSG_801 machinetalk_Preview

#define PREVIEW_MESSAGES \
	PB_MSG(800,81,machinetalk_Position) \
	PB_MSG(801,-1,machinetalk_Preview) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
