/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_RTAPI_MESSAGE_NPB_H_INCLUDED
#define PB_RTAPI_MESSAGE_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#include "machinetalk/protobuf/value.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _machinetalk_RTAPI_Message {
    int32_t msglevel;
    char format[100];
    pb_size_t arg_count;
    machinetalk_Value arg[10];
} machinetalk_RTAPI_Message;

/* Default values for struct fields */
extern const char machinetalk_RTAPI_Message_format_default[100];

/* Initializer values for message structs */
#define machinetalk_RTAPI_Message_init_default   {0, "*** uninitialized ***", 0, {machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default, machinetalk_Value_init_default}}
#define machinetalk_RTAPI_Message_init_zero      {0, "", 0, {machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero, machinetalk_Value_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_RTAPI_Message_msglevel_tag   10
#define machinetalk_RTAPI_Message_format_tag     20
#define machinetalk_RTAPI_Message_arg_tag        30

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_RTAPI_Message_fields[4];

/* Maximum encoded size of messages (where known) */
#define machinetalk_RTAPI_Message_size           (184 + 10*machinetalk_Value_size)

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_1000 machinetalk_RTAPI_Message

#define RTAPI_MESSAGE_MESSAGES \
	PB_MSG(1000,(184 + 10*machinetalk_Value_size),machinetalk_RTAPI_Message) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
