/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_RTAPICOMMAND_NPB_H_INCLUDED
#define PB_RTAPICOMMAND_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _machinetalk_RTAPICommand {
    int32_t instance;
    pb_callback_t modname;
    bool has_rt_msglevel;
    int32_t rt_msglevel;
    bool has_user_msglevel;
    int32_t user_msglevel;
    pb_callback_t argv;
    pb_callback_t threadname;
    bool has_threadperiod;
    int32_t threadperiod;
    bool has_use_fp;
    bool use_fp;
    bool has_cpu;
    int32_t cpu;
    pb_callback_t comp;
    pb_callback_t func;
    pb_callback_t instname;
    bool has_flags;
    int32_t flags;
} machinetalk_RTAPICommand;

/* Default values for struct fields */

/* Initializer values for message structs */
#define machinetalk_RTAPICommand_init_default    {0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define machinetalk_RTAPICommand_init_zero       {0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_RTAPICommand_instance_tag    1
#define machinetalk_RTAPICommand_modname_tag     2
#define machinetalk_RTAPICommand_rt_msglevel_tag 3
#define machinetalk_RTAPICommand_user_msglevel_tag 4
#define machinetalk_RTAPICommand_argv_tag        5
#define machinetalk_RTAPICommand_threadname_tag  6
#define machinetalk_RTAPICommand_threadperiod_tag 7
#define machinetalk_RTAPICommand_use_fp_tag      8
#define machinetalk_RTAPICommand_cpu_tag         9
#define machinetalk_RTAPICommand_comp_tag        10
#define machinetalk_RTAPICommand_func_tag        11
#define machinetalk_RTAPICommand_instname_tag    12
#define machinetalk_RTAPICommand_flags_tag       13

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_RTAPICommand_fields[14];

/* Maximum encoded size of messages (where known) */

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_900 machinetalk_RTAPICommand

#define RTAPICOMMAND_MESSAGES \
	PB_MSG(900,-1,machinetalk_RTAPICommand) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
