/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_STATUS_NPB_H_INCLUDED
#define PB_STATUS_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#include "machinetalk/protobuf/types.npb.h"
#include "machinetalk/protobuf/preview.npb.h"
#include "machinetalk/protobuf/emcclass.npb.h"
#include "machinetalk/protobuf/motcmds.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _machinetalk_EmcTaskExecStateType {
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_ERROR = 1,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_DONE = 2,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_MOTION = 3,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_MOTION_QUEUE = 4,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_IO = 5,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_MOTION_AND_IO = 7,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_DELAY = 8,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_SYSTEM_CMD = 9,
    machinetalk_EmcTaskExecStateType_EMC_TASK_EXEC_WAITING_FOR_SPINDLE_ORIENTED = 10
} machinetalk_EmcTaskExecStateType;

typedef enum _machinetalk_EmcInterpStateType {
    machinetalk_EmcInterpStateType_EMC_TASK_INTERP_IDLE = 1,
    machinetalk_EmcInterpStateType_EMC_TASK_INTERP_READING = 2,
    machinetalk_EmcInterpStateType_EMC_TASK_INTERP_PAUSED = 3,
    machinetalk_EmcInterpStateType_EMC_TASK_INTERP_WAITING = 4
} machinetalk_EmcInterpStateType;

typedef enum _machinetalk_EmcInterpExitCodeType {
    machinetalk_EmcInterpExitCodeType_EMC_INTERP_EXIT_OK = 0,
    machinetalk_EmcInterpExitCodeType_EMC_INTERP_EXIT_EXIT = 1,
    machinetalk_EmcInterpExitCodeType_EMC_INTERP_EXIT_EXECUTE_FINISH = 2,
    machinetalk_EmcInterpExitCodeType_EMC_INTERP_EXIT_ENDFILE = 3,
    machinetalk_EmcInterpExitCodeType_EMC_INTERP_EXIT_FILE_NOT_OPEN = 4,
    machinetalk_EmcInterpExitCodeType_EMC_INTERP_EXIT_ERROR = 5
} machinetalk_EmcInterpExitCodeType;

typedef enum _machinetalk_EmcKinematicsType {
    machinetalk_EmcKinematicsType_KINEMATICS_IDENTITY = 1,
    machinetalk_EmcKinematicsType_KINEMATICS_FORWARD_ONLY = 2,
    machinetalk_EmcKinematicsType_KINEMATICS_INVERSE_ONLY = 3,
    machinetalk_EmcKinematicsType_KINEMATICS_BOTH = 4
} machinetalk_EmcKinematicsType;

typedef enum _machinetalk_EmcTrajectoryModeType {
    machinetalk_EmcTrajectoryModeType_EMC_TRAJ_MODE_FREE = 1,
    machinetalk_EmcTrajectoryModeType_EMC_TRAJ_MODE_COORD = 2,
    machinetalk_EmcTrajectoryModeType_EMC_TRAJ_MODE_TELEOP = 3
} machinetalk_EmcTrajectoryModeType;

typedef enum _machinetalk_EmcCanonUnitsType {
    machinetalk_EmcCanonUnitsType_CANON_UNITS_INCH = 1,
    machinetalk_EmcCanonUnitsType_CANON_UNITS_MM = 2,
    machinetalk_EmcCanonUnitsType_CANON_UNITS_CM = 3
} machinetalk_EmcCanonUnitsType;

typedef enum _machinetalk_EmcLinearUnitsType {
    machinetalk_EmcLinearUnitsType_LINEAR_UNITS_INCH = 1,
    machinetalk_EmcLinearUnitsType_LINEAR_UNITS_MM = 2,
    machinetalk_EmcLinearUnitsType_LINEAR_UNITS_CM = 3
} machinetalk_EmcLinearUnitsType;

typedef enum _machinetalk_EmcAngularUnitsType {
    machinetalk_EmcAngularUnitsType_ANGULAR_UNITS_DEGREES = 1,
    machinetalk_EmcAngularUnitsType_ANGULAR_UNITS_RADIAN = 2,
    machinetalk_EmcAngularUnitsType_ANGULAR_UNITS_GRAD = 3
} machinetalk_EmcAngularUnitsType;

typedef enum _machinetalk_EmcTimeUnitsType {
    machinetalk_EmcTimeUnitsType_TIME_UNITS_MINUTE = 1,
    machinetalk_EmcTimeUnitsType_TIME_UNITS_SECOND = 2
} machinetalk_EmcTimeUnitsType;

typedef enum _machinetalk_EmcTaskModeType {
    machinetalk_EmcTaskModeType_EMC_TASK_MODE_MANUAL = 1,
    machinetalk_EmcTaskModeType_EMC_TASK_MODE_AUTO = 2,
    machinetalk_EmcTaskModeType_EMC_TASK_MODE_MDI = 3
} machinetalk_EmcTaskModeType;

typedef enum _machinetalk_EmcTaskStateType {
    machinetalk_EmcTaskStateType_EMC_TASK_STATE_ESTOP = 1,
    machinetalk_EmcTaskStateType_EMC_TASK_STATE_ESTOP_RESET = 2,
    machinetalk_EmcTaskStateType_EMC_TASK_STATE_OFF = 3,
    machinetalk_EmcTaskStateType_EMC_TASK_STATE_ON = 4
} machinetalk_EmcTaskStateType;

typedef enum _machinetalk_EmcAxisType {
    machinetalk_EmcAxisType_EMC_AXIS_LINEAR = 1,
    machinetalk_EmcAxisType_EMC_AXIS_ANGULAR = 2
} machinetalk_EmcAxisType;

typedef enum _machinetalk_EmcPositionOffsetType {
    machinetalk_EmcPositionOffsetType_EMC_CONFIG_RELATIVE_OFFSET = 1,
    machinetalk_EmcPositionOffsetType_EMC_CONFIG_MACHINE_OFFSET = 2
} machinetalk_EmcPositionOffsetType;

typedef enum _machinetalk_EmcPositionFeedbackType {
    machinetalk_EmcPositionFeedbackType_EMC_CONFIG_ACTUAL_FEEDBACK = 1,
    machinetalk_EmcPositionFeedbackType_EMC_CONFIG_COMMANDED_FEEDBACK = 2
} machinetalk_EmcPositionFeedbackType;

/* Struct definitions */
typedef struct _machinetalk_EmcProgramExtension {
    int32_t index;
    pb_callback_t extension;
} machinetalk_EmcProgramExtension;

typedef struct _machinetalk_EmcStatusAnalogIO {
    int32_t index;
    bool has_value;
    double value;
} machinetalk_EmcStatusAnalogIO;

typedef struct _machinetalk_EmcStatusConfig {
    bool has_default_acceleration;
    double default_acceleration;
    bool has_axes;
    int32_t axes;
    pb_callback_t axis;
    bool has_axis_mask;
    int32_t axis_mask;
    bool has_cycle_time;
    double cycle_time;
    bool has_debug;
    int32_t debug;
    bool has_kinematics_type;
    machinetalk_EmcKinematicsType kinematics_type;
    bool has_max_acceleration;
    double max_acceleration;
    bool has_max_velocity;
    double max_velocity;
    bool has_linear_units;
    machinetalk_EmcLinearUnitsType linear_units;
    bool has_default_velocity;
    double default_velocity;
    pb_callback_t program_extension;
    bool has_position_offset;
    machinetalk_EmcPositionOffsetType position_offset;
    bool has_position_feedback;
    machinetalk_EmcPositionFeedbackType position_feedback;
    bool has_max_feed_override;
    double max_feed_override;
    bool has_min_feed_override;
    double min_feed_override;
    bool has_max_spindle_override;
    double max_spindle_override;
    bool has_min_spindle_override;
    double min_spindle_override;
    bool has_default_spindle_speed;
    double default_spindle_speed;
    bool has_default_linear_velocity;
    double default_linear_velocity;
    bool has_min_velocity;
    double min_velocity;
    bool has_max_linear_velocity;
    double max_linear_velocity;
    bool has_min_linear_velocity;
    double min_linear_velocity;
    bool has_default_angular_velocity;
    double default_angular_velocity;
    bool has_max_angular_velocity;
    double max_angular_velocity;
    bool has_min_angular_velocity;
    double min_angular_velocity;
    pb_callback_t increments;
    pb_callback_t grids;
    bool has_lathe;
    bool lathe;
    pb_callback_t geometry;
    bool has_arcdivision;
    uint32_t arcdivision;
    bool has_no_force_homing;
    bool no_force_homing;
    pb_callback_t remote_path;
    bool has_time_units;
    machinetalk_EmcTimeUnitsType time_units;
    pb_callback_t name;
    pb_callback_t user_command;
    bool has_angular_units;
    machinetalk_EmcAngularUnitsType angular_units;
} machinetalk_EmcStatusConfig;

typedef struct _machinetalk_EmcStatusConfigAxis {
    int32_t index;
    bool has_axis_type;
    machinetalk_EmcAxisType axis_type;
    bool has_backlash;
    double backlash;
    bool has_max_ferror;
    double max_ferror;
    bool has_max_position_limit;
    double max_position_limit;
    bool has_min_ferror;
    double min_ferror;
    bool has_min_position_limit;
    double min_position_limit;
    bool has_home_sequence;
    int32_t home_sequence;
    bool has_max_acceleration;
    double max_acceleration;
    bool has_max_velocity;
    double max_velocity;
    pb_callback_t increments;
} machinetalk_EmcStatusConfigAxis;

typedef struct _machinetalk_EmcStatusDigitalIO {
    int32_t index;
    bool has_value;
    bool value;
} machinetalk_EmcStatusDigitalIO;

typedef struct _machinetalk_EmcStatusGCode {
    int32_t index;
    bool has_value;
    int32_t value;
} machinetalk_EmcStatusGCode;

typedef struct _machinetalk_EmcStatusInterp {
    pb_callback_t command;
    pb_callback_t gcodes;
    bool has_interp_state;
    machinetalk_EmcInterpStateType interp_state;
    bool has_interpreter_errcode;
    machinetalk_EmcInterpExitCodeType interpreter_errcode;
    pb_callback_t mcodes;
    pb_callback_t settings;
    bool has_program_units;
    machinetalk_EmcCanonUnitsType program_units;
} machinetalk_EmcStatusInterp;

typedef struct _machinetalk_EmcStatusIo {
    bool has_estop;
    bool estop;
    bool has_flood;
    bool flood;
    bool has_lube;
    bool lube;
    bool has_lube_level;
    bool lube_level;
    bool has_mist;
    bool mist;
    bool has_tool_offset;
    machinetalk_Position tool_offset;
    pb_callback_t tool_table;
    bool has_pocket_prepped;
    int32_t pocket_prepped;
    bool has_tool_in_spindle;
    int32_t tool_in_spindle;
} machinetalk_EmcStatusIo;

typedef struct _machinetalk_EmcStatusLimit {
    int32_t index;
    bool has_value;
    int32_t value;
} machinetalk_EmcStatusLimit;

typedef struct _machinetalk_EmcStatusMCode {
    int32_t index;
    bool has_value;
    int32_t value;
} machinetalk_EmcStatusMCode;

typedef struct _machinetalk_EmcStatusMotion {
    bool has_active_queue;
    int32_t active_queue;
    bool has_actual_position;
    machinetalk_Position actual_position;
    bool has_adaptive_feed_enabled;
    bool adaptive_feed_enabled;
    pb_callback_t ain;
    pb_callback_t aout;
    pb_callback_t axis;
    bool has_block_delete;
    bool block_delete;
    bool has_current_line;
    int32_t current_line;
    bool has_current_vel;
    double current_vel;
    bool has_delay_left;
    double delay_left;
    pb_callback_t din;
    bool has_distance_to_go;
    double distance_to_go;
    pb_callback_t dout;
    bool has_dtg;
    machinetalk_Position dtg;
    bool has_enabled;
    bool enabled;
    bool has_feed_hold_enabled;
    bool feed_hold_enabled;
    bool has_feed_override_enabled;
    bool feed_override_enabled;
    bool has_feedrate;
    double feedrate;
    bool has_g5x_index;
    machinetalk_OriginIndex g5x_index;
    bool has_g5x_offset;
    machinetalk_Position g5x_offset;
    bool has_g92_offset;
    machinetalk_Position g92_offset;
    bool has_id;
    int32_t id;
    bool has_inpos;
    bool inpos;
    bool has_joint_actual_position;
    machinetalk_Position joint_actual_position;
    bool has_joint_position;
    machinetalk_Position joint_position;
    pb_callback_t limit;
    bool has_motion_line;
    int32_t motion_line;
    bool has_motion_type;
    machinetalk_MotionType motion_type;
    bool has_motion_mode;
    machinetalk_EmcTrajectoryModeType motion_mode;
    bool has_paused;
    bool paused;
    bool has_position;
    machinetalk_Position position;
    bool has_probe_tripped;
    bool probe_tripped;
    bool has_probe_val;
    int32_t probe_val;
    bool has_probed_position;
    machinetalk_Position probed_position;
    bool has_probing;
    bool probing;
    bool has_queue;
    int32_t queue;
    bool has_queue_full;
    bool queue_full;
    bool has_rotation_xy;
    double rotation_xy;
    bool has_spindle_brake;
    bool spindle_brake;
    bool has_spindle_direction;
    int32_t spindle_direction;
    bool has_spindle_enabled;
    bool spindle_enabled;
    bool has_spindle_increasing;
    int32_t spindle_increasing;
    bool has_spindle_override_enabled;
    bool spindle_override_enabled;
    bool has_spindle_speed;
    double spindle_speed;
    bool has_spindlerate;
    double spindlerate;
    bool has_state;
    machinetalk_RCS_STATUS state;
    bool has_max_velocity;
    double max_velocity;
    bool has_max_acceleration;
    double max_acceleration;
    bool has_rapidrate;
    double rapidrate;
} machinetalk_EmcStatusMotion;

typedef struct _machinetalk_EmcStatusMotionAxis {
    int32_t index;
    bool has_enabled;
    bool enabled;
    bool has_fault;
    bool fault;
    bool has_ferror_current;
    double ferror_current;
    bool has_ferror_highmark;
    double ferror_highmark;
    bool has_homed;
    bool homed;
    bool has_homing;
    bool homing;
    bool has_inpos;
    bool inpos;
    bool has_input;
    double input;
    bool has_max_hard_limit;
    bool max_hard_limit;
    bool has_max_soft_limit;
    bool max_soft_limit;
    bool has_min_hard_limit;
    bool min_hard_limit;
    bool has_min_soft_limit;
    bool min_soft_limit;
    bool has_output;
    double output;
    bool has_override_limits;
    bool override_limits;
    bool has_velocity;
    double velocity;
} machinetalk_EmcStatusMotionAxis;

typedef struct _machinetalk_EmcStatusSetting {
    int32_t index;
    bool has_value;
    double value;
} machinetalk_EmcStatusSetting;

typedef struct _machinetalk_EmcStatusTask {
    bool has_echo_serial_number;
    int32_t echo_serial_number;
    bool has_exec_state;
    machinetalk_EmcTaskExecStateType exec_state;
    pb_callback_t file;
    bool has_input_timeout;
    bool input_timeout;
    bool has_optional_stop;
    bool optional_stop;
    bool has_read_line;
    int32_t read_line;
    bool has_task_mode;
    machinetalk_EmcTaskModeType task_mode;
    bool has_task_paused;
    int32_t task_paused;
    bool has_task_state;
    machinetalk_EmcTaskStateType task_state;
    bool has_total_lines;
    int32_t total_lines;
} machinetalk_EmcStatusTask;

typedef struct _machinetalk_EmcStatusUserCommand {
    int32_t index;
    pb_callback_t command;
} machinetalk_EmcStatusUserCommand;

typedef struct _machinetalk_EmcToolData {
    int32_t index;
    bool has_id;
    int32_t id;
    bool has_diameter;
    double diameter;
    bool has_frontangle;
    double frontangle;
    bool has_backangle;
    double backangle;
    bool has_orientation;
    int32_t orientation;
    bool has_offset;
    machinetalk_Position offset;
    pb_callback_t comment;
    bool has_pocket;
    int32_t pocket;
} machinetalk_EmcToolData;

typedef struct _machinetalk_EmcCommandParameters {
    bool has_index;
    uint32_t index;
    bool has_debug_level;
    uint32_t debug_level;
    bool has_line_number;
    int32_t line_number;
    bool has_scale;
    double scale;
    bool has_velocity;
    double velocity;
    bool has_distance;
    double distance;
    bool has_value;
    double value;
    bool has_enable;
    bool enable;
    pb_callback_t command;
    pb_callback_t path;
    bool has_task_mode;
    machinetalk_EmcTaskModeType task_mode;
    bool has_task_state;
    machinetalk_EmcTaskStateType task_state;
    bool has_traj_mode;
    machinetalk_EmcTrajectoryModeType traj_mode;
    bool has_pose;
    machinetalk_EmcPose pose;
    bool has_tool_data;
    machinetalk_EmcToolData tool_data;
    pb_callback_t tool_table;
} machinetalk_EmcCommandParameters;

/* Default values for struct fields */

/* Initializer values for message structs */
#define machinetalk_EmcToolData_init_default     {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, machinetalk_Position_init_default, {{NULL}, NULL}, false, 0}
#define machinetalk_EmcStatusMotionAxis_init_default {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_EmcStatusConfigAxis_init_default {0, false, (machinetalk_EmcAxisType)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define machinetalk_EmcProgramExtension_init_default {0, {{NULL}, NULL}}
#define machinetalk_EmcStatusAnalogIO_init_default {0, false, 0}
#define machinetalk_EmcStatusDigitalIO_init_default {0, false, 0}
#define machinetalk_EmcStatusLimit_init_default  {0, false, 0}
#define machinetalk_EmcStatusGCode_init_default  {0, false, 0}
#define machinetalk_EmcStatusMCode_init_default  {0, false, 0}
#define machinetalk_EmcStatusSetting_init_default {0, false, 0}
#define machinetalk_EmcStatusConfig_init_default {false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, (machinetalk_EmcKinematicsType)0, false, 0, false, 0, false, (machinetalk_EmcLinearUnitsType)0, false, 0, {{NULL}, NULL}, false, (machinetalk_EmcPositionOffsetType)0, false, (machinetalk_EmcPositionFeedbackType)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, (machinetalk_EmcTimeUnitsType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcAngularUnitsType)0}
#define machinetalk_EmcStatusMotion_init_default {false, 0, false, machinetalk_Position_init_default, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, machinetalk_Position_init_default, false, 0, false, 0, false, 0, false, 0, false, (machinetalk_OriginIndex)0, false, machinetalk_Position_init_default, false, machinetalk_Position_init_default, false, 0, false, 0, false, machinetalk_Position_init_default, false, machinetalk_Position_init_default, {{NULL}, NULL}, false, 0, false, (machinetalk_MotionType)0, false, (machinetalk_EmcTrajectoryModeType)0, false, 0, false, machinetalk_Position_init_default, false, 0, false, 0, false, machinetalk_Position_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, (machinetalk_RCS_STATUS)0, false, 0, false, 0, false, 0}
#define machinetalk_EmcStatusIo_init_default     {false, 0, false, 0, false, 0, false, 0, false, 0, false, machinetalk_Position_init_default, {{NULL}, NULL}, false, 0, false, 0}
#define machinetalk_EmcStatusTask_init_default   {false, 0, false, (machinetalk_EmcTaskExecStateType)0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, (machinetalk_EmcTaskModeType)0, false, 0, false, (machinetalk_EmcTaskStateType)0, false, 0}
#define machinetalk_EmcStatusInterp_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcInterpStateType)0, false, (machinetalk_EmcInterpExitCodeType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcCanonUnitsType)0}
#define machinetalk_EmcCommandParameters_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcTaskModeType)0, false, (machinetalk_EmcTaskStateType)0, false, (machinetalk_EmcTrajectoryModeType)0, false, machinetalk_EmcPose_init_default, false, machinetalk_EmcToolData_init_default, {{NULL}, NULL}}
#define machinetalk_EmcStatusUserCommand_init_default {0, {{NULL}, NULL}}
#define machinetalk_EmcToolData_init_zero        {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, machinetalk_Position_init_zero, {{NULL}, NULL}, false, 0}
#define machinetalk_EmcStatusMotionAxis_init_zero {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define machinetalk_EmcStatusConfigAxis_init_zero {0, false, (machinetalk_EmcAxisType)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define machinetalk_EmcProgramExtension_init_zero {0, {{NULL}, NULL}}
#define machinetalk_EmcStatusAnalogIO_init_zero  {0, false, 0}
#define machinetalk_EmcStatusDigitalIO_init_zero {0, false, 0}
#define machinetalk_EmcStatusLimit_init_zero     {0, false, 0}
#define machinetalk_EmcStatusGCode_init_zero     {0, false, 0}
#define machinetalk_EmcStatusMCode_init_zero     {0, false, 0}
#define machinetalk_EmcStatusSetting_init_zero   {0, false, 0}
#define machinetalk_EmcStatusConfig_init_zero    {false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, (machinetalk_EmcKinematicsType)0, false, 0, false, 0, false, (machinetalk_EmcLinearUnitsType)0, false, 0, {{NULL}, NULL}, false, (machinetalk_EmcPositionOffsetType)0, false, (machinetalk_EmcPositionFeedbackType)0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, (machinetalk_EmcTimeUnitsType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcAngularUnitsType)0}
#define machinetalk_EmcStatusMotion_init_zero    {false, 0, false, machinetalk_Position_init_zero, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, machinetalk_Position_init_zero, false, 0, false, 0, false, 0, false, 0, false, (machinetalk_OriginIndex)0, false, machinetalk_Position_init_zero, false, machinetalk_Position_init_zero, false, 0, false, 0, false, machinetalk_Position_init_zero, false, machinetalk_Position_init_zero, {{NULL}, NULL}, false, 0, false, (machinetalk_MotionType)0, false, (machinetalk_EmcTrajectoryModeType)0, false, 0, false, machinetalk_Position_init_zero, false, 0, false, 0, false, machinetalk_Position_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, (machinetalk_RCS_STATUS)0, false, 0, false, 0, false, 0}
#define machinetalk_EmcStatusIo_init_zero        {false, 0, false, 0, false, 0, false, 0, false, 0, false, machinetalk_Position_init_zero, {{NULL}, NULL}, false, 0, false, 0}
#define machinetalk_EmcStatusTask_init_zero      {false, 0, false, (machinetalk_EmcTaskExecStateType)0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, (machinetalk_EmcTaskModeType)0, false, 0, false, (machinetalk_EmcTaskStateType)0, false, 0}
#define machinetalk_EmcStatusInterp_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcInterpStateType)0, false, (machinetalk_EmcInterpExitCodeType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcCanonUnitsType)0}
#define machinetalk_EmcCommandParameters_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, (machinetalk_EmcTaskModeType)0, false, (machinetalk_EmcTaskStateType)0, false, (machinetalk_EmcTrajectoryModeType)0, false, machinetalk_EmcPose_init_zero, false, machinetalk_EmcToolData_init_zero, {{NULL}, NULL}}
#define machinetalk_EmcStatusUserCommand_init_zero {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_EmcProgramExtension_index_tag 1
#define machinetalk_EmcProgramExtension_extension_tag 2
#define machinetalk_EmcStatusAnalogIO_index_tag  1
#define machinetalk_EmcStatusAnalogIO_value_tag  2
#define machinetalk_EmcStatusConfig_default_acceleration_tag 1
#define machinetalk_EmcStatusConfig_axes_tag     3
#define machinetalk_EmcStatusConfig_axis_tag     4
#define machinetalk_EmcStatusConfig_axis_mask_tag 5
#define machinetalk_EmcStatusConfig_cycle_time_tag 6
#define machinetalk_EmcStatusConfig_debug_tag    7
#define machinetalk_EmcStatusConfig_kinematics_type_tag 8
#define machinetalk_EmcStatusConfig_max_acceleration_tag 10
#define machinetalk_EmcStatusConfig_max_velocity_tag 11
#define machinetalk_EmcStatusConfig_linear_units_tag 12
#define machinetalk_EmcStatusConfig_default_velocity_tag 13
#define machinetalk_EmcStatusConfig_program_extension_tag 14
#define machinetalk_EmcStatusConfig_position_offset_tag 15
#define machinetalk_EmcStatusConfig_position_feedback_tag 16
#define machinetalk_EmcStatusConfig_max_feed_override_tag 17
#define machinetalk_EmcStatusConfig_min_feed_override_tag 18
#define machinetalk_EmcStatusConfig_max_spindle_override_tag 19
#define machinetalk_EmcStatusConfig_min_spindle_override_tag 20
#define machinetalk_EmcStatusConfig_default_spindle_speed_tag 21
#define machinetalk_EmcStatusConfig_default_linear_velocity_tag 22
#define machinetalk_EmcStatusConfig_min_velocity_tag 23
#define machinetalk_EmcStatusConfig_max_linear_velocity_tag 24
#define machinetalk_EmcStatusConfig_min_linear_velocity_tag 25
#define machinetalk_EmcStatusConfig_default_angular_velocity_tag 26
#define machinetalk_EmcStatusConfig_max_angular_velocity_tag 27
#define machinetalk_EmcStatusConfig_min_angular_velocity_tag 28
#define machinetalk_EmcStatusConfig_increments_tag 29
#define machinetalk_EmcStatusConfig_grids_tag    30
#define machinetalk_EmcStatusConfig_lathe_tag    31
#define machinetalk_EmcStatusConfig_geometry_tag 32
#define machinetalk_EmcStatusConfig_arcdivision_tag 33
#define machinetalk_EmcStatusConfig_no_force_homing_tag 34
#define machinetalk_EmcStatusConfig_remote_path_tag 35
#define machinetalk_EmcStatusConfig_time_units_tag 36
#define machinetalk_EmcStatusConfig_name_tag     37
#define machinetalk_EmcStatusConfig_user_command_tag 38
#define machinetalk_EmcStatusConfig_angular_units_tag 39
#define machinetalk_EmcStatusConfigAxis_index_tag 1
#define machinetalk_EmcStatusConfigAxis_axis_type_tag 2
#define machinetalk_EmcStatusConfigAxis_backlash_tag 3
#define machinetalk_EmcStatusConfigAxis_max_ferror_tag 4
#define machinetalk_EmcStatusConfigAxis_max_position_limit_tag 5
#define machinetalk_EmcStatusConfigAxis_min_ferror_tag 6
#define machinetalk_EmcStatusConfigAxis_min_position_limit_tag 7
#define machinetalk_EmcStatusConfigAxis_home_sequence_tag 9
#define machinetalk_EmcStatusConfigAxis_max_acceleration_tag 10
#define machinetalk_EmcStatusConfigAxis_max_velocity_tag 11
#define machinetalk_EmcStatusConfigAxis_increments_tag 12
#define machinetalk_EmcStatusDigitalIO_index_tag 1
#define machinetalk_EmcStatusDigitalIO_value_tag 2
#define machinetalk_EmcStatusGCode_index_tag     1
#define machinetalk_EmcStatusGCode_value_tag     2
#define machinetalk_EmcStatusInterp_command_tag  1
#define machinetalk_EmcStatusInterp_gcodes_tag   2
#define machinetalk_EmcStatusInterp_interp_state_tag 3
#define machinetalk_EmcStatusInterp_interpreter_errcode_tag 4
#define machinetalk_EmcStatusInterp_mcodes_tag   5
#define machinetalk_EmcStatusInterp_settings_tag 6
#define machinetalk_EmcStatusInterp_program_units_tag 7
#define machinetalk_EmcStatusIo_estop_tag        1
#define machinetalk_EmcStatusIo_flood_tag        2
#define machinetalk_EmcStatusIo_lube_tag         3
#define machinetalk_EmcStatusIo_lube_level_tag   4
#define machinetalk_EmcStatusIo_mist_tag         5
#define machinetalk_EmcStatusIo_tool_offset_tag  8
#define machinetalk_EmcStatusIo_tool_table_tag   9
#define machinetalk_EmcStatusIo_pocket_prepped_tag 10
#define machinetalk_EmcStatusIo_tool_in_spindle_tag 11
#define machinetalk_EmcStatusLimit_index_tag     1
#define machinetalk_EmcStatusLimit_value_tag     2
#define machinetalk_EmcStatusMCode_index_tag     1
#define machinetalk_EmcStatusMCode_value_tag     2
#define machinetalk_EmcStatusMotion_active_queue_tag 1
#define machinetalk_EmcStatusMotion_actual_position_tag 2
#define machinetalk_EmcStatusMotion_adaptive_feed_enabled_tag 3
#define machinetalk_EmcStatusMotion_ain_tag      4
#define machinetalk_EmcStatusMotion_aout_tag     5
#define machinetalk_EmcStatusMotion_axis_tag     6
#define machinetalk_EmcStatusMotion_block_delete_tag 7
#define machinetalk_EmcStatusMotion_current_line_tag 8
#define machinetalk_EmcStatusMotion_current_vel_tag 9
#define machinetalk_EmcStatusMotion_delay_left_tag 10
#define machinetalk_EmcStatusMotion_din_tag      11
#define machinetalk_EmcStatusMotion_distance_to_go_tag 12
#define machinetalk_EmcStatusMotion_dout_tag     13
#define machinetalk_EmcStatusMotion_dtg_tag      14
#define machinetalk_EmcStatusMotion_enabled_tag  15
#define machinetalk_EmcStatusMotion_feed_hold_enabled_tag 16
#define machinetalk_EmcStatusMotion_feed_override_enabled_tag 17
#define machinetalk_EmcStatusMotion_feedrate_tag 18
#define machinetalk_EmcStatusMotion_g5x_index_tag 19
#define machinetalk_EmcStatusMotion_g5x_offset_tag 20
#define machinetalk_EmcStatusMotion_g92_offset_tag 21
#define machinetalk_EmcStatusMotion_id_tag       23
#define machinetalk_EmcStatusMotion_inpos_tag    24
#define machinetalk_EmcStatusMotion_joint_actual_position_tag 25
#define machinetalk_EmcStatusMotion_joint_position_tag 26
#define machinetalk_EmcStatusMotion_limit_tag    27
#define machinetalk_EmcStatusMotion_motion_line_tag 28
#define machinetalk_EmcStatusMotion_motion_type_tag 29
#define machinetalk_EmcStatusMotion_motion_mode_tag 30
#define machinetalk_EmcStatusMotion_paused_tag   31
#define machinetalk_EmcStatusMotion_position_tag 32
#define machinetalk_EmcStatusMotion_probe_tripped_tag 33
#define machinetalk_EmcStatusMotion_probe_val_tag 34
#define machinetalk_EmcStatusMotion_probed_position_tag 35
#define machinetalk_EmcStatusMotion_probing_tag  36
#define machinetalk_EmcStatusMotion_queue_tag    37
#define machinetalk_EmcStatusMotion_queue_full_tag 38
#define machinetalk_EmcStatusMotion_rotation_xy_tag 39
#define machinetalk_EmcStatusMotion_spindle_brake_tag 40
#define machinetalk_EmcStatusMotion_spindle_direction_tag 41
#define machinetalk_EmcStatusMotion_spindle_enabled_tag 42
#define machinetalk_EmcStatusMotion_spindle_increasing_tag 43
#define machinetalk_EmcStatusMotion_spindle_override_enabled_tag 44
#define machinetalk_EmcStatusMotion_spindle_speed_tag 45
#define machinetalk_EmcStatusMotion_spindlerate_tag 46
#define machinetalk_EmcStatusMotion_state_tag    47
#define machinetalk_EmcStatusMotion_max_velocity_tag 48
#define machinetalk_EmcStatusMotion_max_acceleration_tag 49
#define machinetalk_EmcStatusMotion_rapidrate_tag 50
#define machinetalk_EmcStatusMotionAxis_index_tag 1
#define machinetalk_EmcStatusMotionAxis_enabled_tag 2
#define machinetalk_EmcStatusMotionAxis_fault_tag 3
#define machinetalk_EmcStatusMotionAxis_ferror_current_tag 4
#define machinetalk_EmcStatusMotionAxis_ferror_highmark_tag 5
#define machinetalk_EmcStatusMotionAxis_homed_tag 6
#define machinetalk_EmcStatusMotionAxis_homing_tag 7
#define machinetalk_EmcStatusMotionAxis_inpos_tag 8
#define machinetalk_EmcStatusMotionAxis_input_tag 9
#define machinetalk_EmcStatusMotionAxis_max_hard_limit_tag 10
#define machinetalk_EmcStatusMotionAxis_max_soft_limit_tag 11
#define machinetalk_EmcStatusMotionAxis_min_hard_limit_tag 12
#define machinetalk_EmcStatusMotionAxis_min_soft_limit_tag 13
#define machinetalk_EmcStatusMotionAxis_output_tag 14
#define machinetalk_EmcStatusMotionAxis_override_limits_tag 15
#define machinetalk_EmcStatusMotionAxis_velocity_tag 16
#define machinetalk_EmcStatusSetting_index_tag   1
#define machinetalk_EmcStatusSetting_value_tag   2
#define machinetalk_EmcStatusTask_echo_serial_number_tag 1
#define machinetalk_EmcStatusTask_exec_state_tag 2
#define machinetalk_EmcStatusTask_file_tag       3
#define machinetalk_EmcStatusTask_input_timeout_tag 4
#define machinetalk_EmcStatusTask_optional_stop_tag 5
#define machinetalk_EmcStatusTask_read_line_tag  6
#define machinetalk_EmcStatusTask_task_mode_tag  7
#define machinetalk_EmcStatusTask_task_paused_tag 8
#define machinetalk_EmcStatusTask_task_state_tag 9
#define machinetalk_EmcStatusTask_total_lines_tag 10
#define machinetalk_EmcStatusUserCommand_index_tag 1
#define machinetalk_EmcStatusUserCommand_command_tag 2
#define machinetalk_EmcToolData_index_tag        1
#define machinetalk_EmcToolData_id_tag           2
#define machinetalk_EmcToolData_diameter_tag     12
#define machinetalk_EmcToolData_frontangle_tag   13
#define machinetalk_EmcToolData_backangle_tag    14
#define machinetalk_EmcToolData_orientation_tag  15
#define machinetalk_EmcToolData_offset_tag       16
#define machinetalk_EmcToolData_comment_tag      17
#define machinetalk_EmcToolData_pocket_tag       18
#define machinetalk_EmcCommandParameters_index_tag 1
#define machinetalk_EmcCommandParameters_debug_level_tag 2
#define machinetalk_EmcCommandParameters_line_number_tag 3
#define machinetalk_EmcCommandParameters_scale_tag 4
#define machinetalk_EmcCommandParameters_velocity_tag 5
#define machinetalk_EmcCommandParameters_distance_tag 6
#define machinetalk_EmcCommandParameters_value_tag 7
#define machinetalk_EmcCommandParameters_enable_tag 8
#define machinetalk_EmcCommandParameters_command_tag 9
#define machinetalk_EmcCommandParameters_path_tag 10
#define machinetalk_EmcCommandParameters_task_mode_tag 100
#define machinetalk_EmcCommandParameters_task_state_tag 101
#define machinetalk_EmcCommandParameters_traj_mode_tag 102
#define machinetalk_EmcCommandParameters_pose_tag 103
#define machinetalk_EmcCommandParameters_tool_data_tag 104
#define machinetalk_EmcCommandParameters_tool_table_tag 105

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_EmcToolData_fields[10];
extern const pb_field_t machinetalk_EmcStatusMotionAxis_fields[17];
extern const pb_field_t machinetalk_EmcStatusConfigAxis_fields[12];
extern const pb_field_t machinetalk_EmcProgramExtension_fields[3];
extern const pb_field_t machinetalk_EmcStatusAnalogIO_fields[3];
extern const pb_field_t machinetalk_EmcStatusDigitalIO_fields[3];
extern const pb_field_t machinetalk_EmcStatusLimit_fields[3];
extern const pb_field_t machinetalk_EmcStatusGCode_fields[3];
extern const pb_field_t machinetalk_EmcStatusMCode_fields[3];
extern const pb_field_t machinetalk_EmcStatusSetting_fields[3];
extern const pb_field_t machinetalk_EmcStatusConfig_fields[38];
extern const pb_field_t machinetalk_EmcStatusMotion_fields[50];
extern const pb_field_t machinetalk_EmcStatusIo_fields[10];
extern const pb_field_t machinetalk_EmcStatusTask_fields[11];
extern const pb_field_t machinetalk_EmcStatusInterp_fields[8];
extern const pb_field_t machinetalk_EmcCommandParameters_fields[17];
extern const pb_field_t machinetalk_EmcStatusUserCommand_fields[3];

/* Maximum encoded size of messages (where known) */
#define machinetalk_EmcStatusMotionAxis_size     77
#define machinetalk_EmcStatusAnalogIO_size       20
#define machinetalk_EmcStatusDigitalIO_size      13
#define machinetalk_EmcStatusLimit_size          22
#define machinetalk_EmcStatusGCode_size          22
#define machinetalk_EmcStatusMCode_size          22
#define machinetalk_EmcStatusSetting_size        20

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_1100 machinetalk_EmcToolData
#define PB_MSG_1101 machinetalk_EmcStatusMotionAxis
#define PB_MSG_1102 machinetalk_EmcStatusConfigAxis
#define PB_MSG_1103 machinetalk_EmcProgramExtension
#define PB_MSG_1104 machinetalk_EmcStatusAnalogIO
#define PB_MSG_1105 machinetalk_EmcStatusDigitalIO
#define PB_MSG_1106 machinetalk_EmcStatusLimit
#define PB_MSG_1107 machinetalk_EmcStatusGCode
#define PB_MSG_1108 machinetalk_EmcStatusMCode
#define PB_MSG_1109 machinetalk_EmcStatusSetting
#define PB_MSG_1110 machinetalk_EmcStatusConfig
#define PB_MSG_1111 machinetalk_EmcStatusMotion
#define PB_MSG_1112 machinetalk_EmcStatusIo
#define PB_MSG_1113 machinetalk_EmcStatusTask
#define PB_MSG_1114 machinetalk_EmcStatusInterp
#define PB_MSG_1115 machinetalk_EmcCommandParameters
#define PB_MSG_1116 machinetalk_EmcStatusUserCommand

#define STATUS_MESSAGES \
	PB_MSG(1100,-1,machinetalk_EmcToolData) \
	PB_MSG(1101,77,machinetalk_EmcStatusMotionAxis) \
	PB_MSG(1102,-1,machinetalk_EmcStatusConfigAxis) \
	PB_MSG(1103,-1,machinetalk_EmcProgramExtension) \
	PB_MSG(1104,20,machinetalk_EmcStatusAnalogIO) \
	PB_MSG(1105,13,machinetalk_EmcStatusDigitalIO) \
	PB_MSG(1106,22,machinetalk_EmcStatusLimit) \
	PB_MSG(1107,22,machinetalk_EmcStatusGCode) \
	PB_MSG(1108,22,machinetalk_EmcStatusMCode) \
	PB_MSG(1109,20,machinetalk_EmcStatusSetting) \
	PB_MSG(1110,-1,machinetalk_EmcStatusConfig) \
	PB_MSG(1111,-1,machinetalk_EmcStatusMotion) \
	PB_MSG(1112,-1,machinetalk_EmcStatusIo) \
	PB_MSG(1113,-1,machinetalk_EmcStatusTask) \
	PB_MSG(1114,-1,machinetalk_EmcStatusInterp) \
	PB_MSG(1115,-1,machinetalk_EmcCommandParameters) \
	PB_MSG(1116,-1,machinetalk_EmcStatusUserCommand) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
