/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_TASK_NPB_H_INCLUDED
#define PB_TASK_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/types.npb.h"
#include "machinetalk/protobuf/nanopb.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _machinetalk_TaskPlanOpen {
    pb_callback_t filename;
} machinetalk_TaskPlanOpen;

typedef struct _machinetalk_TaskPlanBlockDelete {
    bool state;
} machinetalk_TaskPlanBlockDelete;

typedef struct _machinetalk_TaskPlanExecute {
    pb_callback_t command;
    bool has_line;
    int32_t line;
} machinetalk_TaskPlanExecute;

typedef struct _machinetalk_TaskPlanOptionalStop {
    bool state;
} machinetalk_TaskPlanOptionalStop;

typedef struct _machinetalk_TaskPlanReply {
    machinetalk_ContainerType cmd;
    pb_callback_t errormsg;
} machinetalk_TaskPlanReply;

typedef struct _machinetalk_TaskReply {
    uint32_t ticket;
} machinetalk_TaskReply;

typedef struct _machinetalk_TicketUpdate {
    uint32_t cticket;
    machinetalk_RCS_STATUS status;
    pb_callback_t text;
} machinetalk_TicketUpdate;

/* Default values for struct fields */

/* Initializer values for message structs */
#define machinetalk_TaskPlanExecute_init_default {{{NULL}, NULL}, false, 0}
#define machinetalk_TaskPlanBlockDelete_init_default {0}
#define machinetalk_TaskPlanOptionalStop_init_default {0}
#define machinetalk_TaskPlanOpen_init_default    {{{NULL}, NULL}}
#define machinetalk_TaskPlanReply_init_default   {(machinetalk_ContainerType)0, {{NULL}, NULL}}
#define machinetalk_TaskReply_init_default       {0}
#define machinetalk_TicketUpdate_init_default    {0, (machinetalk_RCS_STATUS)0, {{NULL}, NULL}}
#define machinetalk_TaskPlanExecute_init_zero    {{{NULL}, NULL}, false, 0}
#define machinetalk_TaskPlanBlockDelete_init_zero {0}
#define machinetalk_TaskPlanOptionalStop_init_zero {0}
#define machinetalk_TaskPlanOpen_init_zero       {{{NULL}, NULL}}
#define machinetalk_TaskPlanReply_init_zero      {(machinetalk_ContainerType)0, {{NULL}, NULL}}
#define machinetalk_TaskReply_init_zero          {0}
#define machinetalk_TicketUpdate_init_zero       {0, (machinetalk_RCS_STATUS)0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define machinetalk_TaskPlanOpen_filename_tag    10
#define machinetalk_TaskPlanBlockDelete_state_tag 10
#define machinetalk_TaskPlanExecute_command_tag  10
#define machinetalk_TaskPlanExecute_line_tag     30
#define machinetalk_TaskPlanOptionalStop_state_tag 10
#define machinetalk_TaskPlanReply_cmd_tag        10
#define machinetalk_TaskPlanReply_errormsg_tag   20
#define machinetalk_TaskReply_ticket_tag         10
#define machinetalk_TicketUpdate_cticket_tag     10
#define machinetalk_TicketUpdate_status_tag      20
#define machinetalk_TicketUpdate_text_tag        30

/* Struct field encoding specification for nanopb */
extern const pb_field_t machinetalk_TaskPlanExecute_fields[3];
extern const pb_field_t machinetalk_TaskPlanBlockDelete_fields[2];
extern const pb_field_t machinetalk_TaskPlanOptionalStop_fields[2];
extern const pb_field_t machinetalk_TaskPlanOpen_fields[2];
extern const pb_field_t machinetalk_TaskPlanReply_fields[3];
extern const pb_field_t machinetalk_TaskReply_fields[2];
extern const pb_field_t machinetalk_TicketUpdate_fields[4];

/* Maximum encoded size of messages (where known) */
#define machinetalk_TaskPlanBlockDelete_size     2
#define machinetalk_TaskPlanOptionalStop_size    2
#define machinetalk_TaskReply_size               5

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID
#define PB_MSG_1200 machinetalk_TaskPlanExecute
#define PB_MSG_1201 machinetalk_TaskPlanBlockDelete
#define PB_MSG_1202 machinetalk_TaskPlanOptionalStop
#define PB_MSG_1203 machinetalk_TaskPlanOpen
#define PB_MSG_1204 machinetalk_TaskPlanReply
#define PB_MSG_1205 machinetalk_TaskReply
#define PB_MSG_1206 machinetalk_TicketUpdate

#define TASK_MESSAGES \
	PB_MSG(1200,-1,machinetalk_TaskPlanExecute) \
	PB_MSG(1201,2,machinetalk_TaskPlanBlockDelete) \
	PB_MSG(1202,2,machinetalk_TaskPlanOptionalStop) \
	PB_MSG(1203,-1,machinetalk_TaskPlanOpen) \
	PB_MSG(1204,-1,machinetalk_TaskPlanReply) \
	PB_MSG(1205,5,machinetalk_TaskReply) \
	PB_MSG(1206,-1,machinetalk_TicketUpdate) \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
