/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.3-dev at Thu Mar 16 16:47:33 2017. */

#ifndef PB_TYPES_NPB_H_INCLUDED
#define PB_TYPES_NPB_H_INCLUDED
#include <pb.h>

#include "machinetalk/protobuf/nanopb.npb.h"
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _machinetalk_ValueType {
    machinetalk_ValueType_HAL_BIT = 1,
    machinetalk_ValueType_HAL_FLOAT = 2,
    machinetalk_ValueType_HAL_S32 = 3,
    machinetalk_ValueType_HAL_U32 = 4,
    machinetalk_ValueType_HAL_S64 = 5,
    machinetalk_ValueType_HAL_U64 = 6,
    machinetalk_ValueType_STRING = 7,
    machinetalk_ValueType_BYTES = 8,
    machinetalk_ValueType_INT32 = 20,
    machinetalk_ValueType_UINT32 = 30,
    machinetalk_ValueType_INT64 = 40,
    machinetalk_ValueType_UINT64 = 50,
    machinetalk_ValueType_DOUBLE = 60,
    machinetalk_ValueType_BOOL = 80,
    machinetalk_ValueType_CARTESIAN = 100,
    machinetalk_ValueType_LEGACY_CARTESIAN = 110,
    machinetalk_ValueType_POSE = 120,
    machinetalk_ValueType_LEGACY_POSE = 130
} machinetalk_ValueType;

typedef enum _machinetalk_HalPinDirection {
    machinetalk_HalPinDirection_HAL_IN = 16,
    machinetalk_HalPinDirection_HAL_OUT = 32,
    machinetalk_HalPinDirection_HAL_IO = 48
} machinetalk_HalPinDirection;

typedef enum _machinetalk_HalParamDirection {
    machinetalk_HalParamDirection_HAL_RO = 64,
    machinetalk_HalParamDirection_HAL_RW = 192
} machinetalk_HalParamDirection;

typedef enum _machinetalk_HalFunctType {
    machinetalk_HalFunctType_FS_LEGACY_THREADFUNC = 0,
    machinetalk_HalFunctType_FS_XTHREADFUNC = 1,
    machinetalk_HalFunctType_FS_USERLAND = 2
} machinetalk_HalFunctType;

typedef enum _machinetalk_ObjectType {
    machinetalk_ObjectType_HAL_OBJECT_INVALID = 0,
    machinetalk_ObjectType_HAL_PIN = 1,
    machinetalk_ObjectType_HAL_SIGNAL = 2,
    machinetalk_ObjectType_HAL_PARAM = 3,
    machinetalk_ObjectType_HAL_THREAD = 4,
    machinetalk_ObjectType_HAL_FUNCT = 5,
    machinetalk_ObjectType_HAL_COMPONENT = 6,
    machinetalk_ObjectType_HAL_VTABLE = 7,
    machinetalk_ObjectType_HAL_INST = 8,
    machinetalk_ObjectType_HAL_RING = 9,
    machinetalk_ObjectType_HAL_GROUP = 10,
    machinetalk_ObjectType_HAL_MEMBER = 11,
    machinetalk_ObjectType_HAL_PLUG = 12
} machinetalk_ObjectType;

typedef enum _machinetalk_msgidType {
    machinetalk_msgidType_MSGID_MAX = 4000,
    machinetalk_msgidType_MSGID_ROUTE_DELIMITER = 4001,
    machinetalk_msgidType_MSGID_ERROR_MSG = 4002,
    machinetalk_msgidType_MSGID_BLOB = 4003,
    machinetalk_msgidType_MSGID_STRING = 4004,
    machinetalk_msgidType_MSGID_HOP = 4005
} machinetalk_msgidType;

typedef enum _machinetalk_socketType {
    machinetalk_socketType_ST_ZMQ_PAIR = 0,
    machinetalk_socketType_ST_ZMQ_PUB = 1,
    machinetalk_socketType_ST_ZMQ_SUB = 2,
    machinetalk_socketType_ST_ZMQ_REQ = 3,
    machinetalk_socketType_ST_ZMQ_REP = 4,
    machinetalk_socketType_ST_ZMQ_DEALER = 5,
    machinetalk_socketType_ST_ZMQ_ROUTER = 6,
    machinetalk_socketType_ST_ZMQ_PULL = 7,
    machinetalk_socketType_ST_ZMQ_PUSH = 8,
    machinetalk_socketType_ST_ZMQ_XPUB = 9,
    machinetalk_socketType_ST_ZMQ_XSUB = 10,
    machinetalk_socketType_ST_ZMQ_STREAM = 11,
    machinetalk_socketType_ST_ZMQ_INVALID = 15
} machinetalk_socketType;

typedef enum _machinetalk_securityMechanism {
    machinetalk_securityMechanism_SM_ZMQ_NONE = -1,
    machinetalk_securityMechanism_SM_ZMQ_NULL = 0,
    machinetalk_securityMechanism_SM_ZMQ_PLAIN = 1,
    machinetalk_securityMechanism_SM_ZMQ_CURVE = 2
} machinetalk_securityMechanism;

typedef enum _machinetalk_RCS_STATUS {
    machinetalk_RCS_STATUS_UNINITIALIZED_STATUS = -1,
    machinetalk_RCS_STATUS_RCS_DONE = 1,
    machinetalk_RCS_STATUS_RCS_EXEC = 2,
    machinetalk_RCS_STATUS_RCS_ERROR = 3,
    machinetalk_RCS_STATUS_RCS_RECEIVED = 4
} machinetalk_RCS_STATUS;

typedef enum _machinetalk_MsgOrigin {
    machinetalk_MsgOrigin_MSG_KERNEL = 0,
    machinetalk_MsgOrigin_MSG_RTUSER = 1,
    machinetalk_MsgOrigin_MSG_ULAPI = 2
} machinetalk_MsgOrigin;

typedef enum _machinetalk_MsgLevel {
    machinetalk_MsgLevel_RTAPI_MSG_NONE = 0,
    machinetalk_MsgLevel_RTAPI_MSG_ERR = 1,
    machinetalk_MsgLevel_RTAPI_MSG_WARN = 2,
    machinetalk_MsgLevel_RTAPI_MSG_INFO = 3,
    machinetalk_MsgLevel_RTAPI_MSG_DBG = 4,
    machinetalk_MsgLevel_RTAPI_MSG_ALL = 5
} machinetalk_MsgLevel;

typedef enum _machinetalk_OriginDetail {
    machinetalk_OriginDetail_UNIX_SIGNAL = 10,
    machinetalk_OriginDetail_INSTANCE_SHUTDOWN = 20,
    machinetalk_OriginDetail_ZMQ_SOCKET = 70,
    machinetalk_OriginDetail_NML_LAYER = 80,
    machinetalk_OriginDetail_RCS_LAYER = 90,
    machinetalk_OriginDetail_CMS_LAYER = 100,
    machinetalk_OriginDetail_IP_LAYER = 110,
    machinetalk_OriginDetail_TCP_LAYER = 120,
    machinetalk_OriginDetail_PGM_LAYER = 130
} machinetalk_OriginDetail;

typedef enum _machinetalk_OriginType {
    machinetalk_OriginType_PROCESS = 10,
    machinetalk_OriginType_USER_THREAD = 20,
    machinetalk_OriginType_RT_THREAD = 30,
    machinetalk_OriginType_COMPONENT = 40,
    machinetalk_OriginType_THREAD_FUNCTION = 50,
    machinetalk_OriginType_COMPONENT_INIT = 60,
    machinetalk_OriginType_COMPONENT_EXIT = 70,
    machinetalk_OriginType_GROUP = 80,
    machinetalk_OriginType_PIN = 90,
    machinetalk_OriginType_SIGNAL = 100
} machinetalk_OriginType;

typedef enum _machinetalk_Severity {
    machinetalk_Severity_S_INFORMATIONAL = 1,
    machinetalk_Severity_S_WARNING = 2,
    machinetalk_Severity_S_FAIL = 4
} machinetalk_Severity;

typedef enum _machinetalk_StatusType {
    machinetalk_StatusType_ENQUEUED = 1,
    machinetalk_StatusType_PROCESSING = 2,
    machinetalk_StatusType_COMPLETE = 3,
    machinetalk_StatusType_FAILED = 4
} machinetalk_StatusType;

typedef enum _machinetalk_ReplyType {
    machinetalk_ReplyType_NONE = 0,
    machinetalk_ReplyType_ON_RECEPTION = 1,
    machinetalk_ReplyType_ON_QUEUED = 2,
    machinetalk_ReplyType_ON_COMPLETION = 4,
    machinetalk_ReplyType_ALL_STEPS = 255
} machinetalk_ReplyType;

typedef enum _machinetalk_ServiceType {
    machinetalk_ServiceType_ST_LOGGING = 1,
    machinetalk_ServiceType_ST_CONFIG = 2,
    machinetalk_ServiceType_ST_REDIS = 3,
    machinetalk_ServiceType_ST_HTTP = 4,
    machinetalk_ServiceType_ST_HTTPS = 5,
    machinetalk_ServiceType_ST_WEBSOCKET = 6,
    machinetalk_ServiceType_ST_WEBSOCKETS = 7,
    machinetalk_ServiceType_ST_RTAPI_COMMAND = 8,
    machinetalk_ServiceType_ST_STP_HALGROUP = 9,
    machinetalk_ServiceType_ST_STP_HALRCOMP = 10,
    machinetalk_ServiceType_ST_STP_INTERP = 11,
    machinetalk_ServiceType_ST_STP_TASK = 12,
    machinetalk_ServiceType_ST_HAL_RCOMMAND = 13,
    machinetalk_ServiceType_ST_TASK_COMMAND = 14,
    machinetalk_ServiceType_ST_INTERP_COMMAND = 15,
    machinetalk_ServiceType_ST_MESSAGEBUS_COMMAND = 16,
    machinetalk_ServiceType_ST_MESSAGEBUS_RESPONSE = 17
} machinetalk_ServiceType;

typedef enum _machinetalk_ServiceAPI {
    machinetalk_ServiceAPI_SA_ZMQ_PROTOBUF = 1,
    machinetalk_ServiceAPI_SA_WS_JSON = 2
} machinetalk_ServiceAPI;

typedef enum _machinetalk_ContainerType {
    machinetalk_ContainerType_MT_RTMESSAGE = 2,
    machinetalk_ContainerType_MT_MOTCMD = 3,
    machinetalk_ContainerType_MT_MOTSTATUS = 4,
    machinetalk_ContainerType_MT_LEGACY_MOTCMD = 5,
    machinetalk_ContainerType_MT_LEGACY_MOTSTATUS = 6,
    machinetalk_ContainerType_MT_WOU = 7,
    machinetalk_ContainerType_MT_HALUPDATE = 8,
    machinetalk_ContainerType_MT_RTAPI_MESSAGE = 9,
    machinetalk_ContainerType_MT_LOG_MESSAGE = 10,
    machinetalk_ContainerType_MT_PREVIEW = 11,
    machinetalk_ContainerType_MT_PROGRESS = 12,
    machinetalk_ContainerType_MT_INTERP_STAT = 13,
    machinetalk_ContainerType_MT_SYSLOG = 18,
    machinetalk_ContainerType_MT_LEGACY_NML = 19,
    machinetalk_ContainerType_MT_LEGACY_MOTCONFIG = 20,
    machinetalk_ContainerType_MT_STP_UPDATE_FULL = 26,
    machinetalk_ContainerType_MT_STP_UPDATE = 28,
    machinetalk_ContainerType_MT_STP_NOGROUP = 27,
    machinetalk_ContainerType_MT_SHUTDOWN = 45,
    machinetalk_ContainerType_MT_CONFIRM_SHUTDOWN = 50,
    machinetalk_ContainerType_MT_RTMESSAGE0 = 30,
    machinetalk_ContainerType_MT_RTMESSAGE1 = 31,
    machinetalk_ContainerType_MT_RTMESSAGE2 = 32,
    machinetalk_ContainerType_MT_RTMESSAGE3 = 33,
    machinetalk_ContainerType_MT_RTMESSAGE4 = 34,
    machinetalk_ContainerType_MT_ASCII = 100,
    machinetalk_ContainerType_MT_UNICODE = 101,
    machinetalk_ContainerType_MT_GCODE = 102,
    machinetalk_ContainerType_MT_PYTHON = 103,
    machinetalk_ContainerType_MT_PICKLE = 104,
    machinetalk_ContainerType_MT_TCL = 105,
    machinetalk_ContainerType_MT_XML = 106,
    machinetalk_ContainerType_MT_JSON = 107,
    machinetalk_ContainerType_MT_JPEG = 108,
    machinetalk_ContainerType_MT_PNG = 109,
    machinetalk_ContainerType_MT_TIFF = 110,
    machinetalk_ContainerType_MT_POSTSCRIPT = 111,
    machinetalk_ContainerType_MT_SVG = 112,
    machinetalk_ContainerType_MT_ZMQ_SUBSCRIBE = 150,
    machinetalk_ContainerType_MT_ZMQ_UNSUBSCRIBE = 151,
    machinetalk_ContainerType_MT_PING = 210,
    machinetalk_ContainerType_MT_PING_ACKNOWLEDGE = 215,
    machinetalk_ContainerType_MT_REJECT = 220,
    machinetalk_ContainerType_MT_DONE = 240,
    machinetalk_ContainerType_MT_SERVICE_REQUEST = 250,
    machinetalk_ContainerType_MT_SERVICE_ANNOUNCEMENT = 251,
    machinetalk_ContainerType_MT_SERVICE_PROBE = 252,
    machinetalk_ContainerType_MT_MESSAGEBUS_NO_DESTINATION = 255,
    machinetalk_ContainerType_MT_HALRCOMP_BIND = 256,
    machinetalk_ContainerType_MT_HALRCOMP_BIND_CONFIRM = 257,
    machinetalk_ContainerType_MT_HALRCOMP_BIND_REJECT = 258,
    machinetalk_ContainerType_MT_HALRCOMP_SET = 259,
    machinetalk_ContainerType_MT_HALRCOMP_SET_REJECT = 260,
    machinetalk_ContainerType_MT_HALRCOMP_ACK = 263,
    machinetalk_ContainerType_MT_HALRCOMMAND_SET = 265,
    machinetalk_ContainerType_MT_HALRCOMMAND_SET_REJECT = 266,
    machinetalk_ContainerType_MT_HALRCOMMAND_GET = 267,
    machinetalk_ContainerType_MT_HALRCOMMAND_GET_REJECT = 268,
    machinetalk_ContainerType_MT_HALRCOMMAND_CREATE = 269,
    machinetalk_ContainerType_MT_HALRCOMMAND_CREATE_REJECT = 270,
    machinetalk_ContainerType_MT_HALRCOMMAND_DELETE = 271,
    machinetalk_ContainerType_MT_HALRCOMMAND_DELETE_REJECT = 272,
    machinetalk_ContainerType_MT_HALRCOMMAND_ACK = 273,
    machinetalk_ContainerType_MT_HALRCOMMAND_ERROR = 274,
    machinetalk_ContainerType_MT_HALRCOMMAND_DESCRIBE = 276,
    machinetalk_ContainerType_MT_HALRCOMMAND_DESCRIPTION = 277,
    machinetalk_ContainerType_MT_HALRCOMP_FULL_UPDATE = 288,
    machinetalk_ContainerType_MT_HALRCOMP_INCREMENTAL_UPDATE = 289,
    machinetalk_ContainerType_MT_HALRCOMP_ERROR = 290,
    machinetalk_ContainerType_MT_HALGROUP_BIND = 294,
    machinetalk_ContainerType_MT_HALGROUP_BIND_CONFIRM = 295,
    machinetalk_ContainerType_MT_HALGROUP_BIND_REJECT = 296,
    machinetalk_ContainerType_MT_HALGROUP_FULL_UPDATE = 297,
    machinetalk_ContainerType_MT_HALGROUP_INCREMENTAL_UPDATE = 298,
    machinetalk_ContainerType_MT_HALGROUP_ERROR = 299,
    machinetalk_ContainerType_MT_RTAPI_APP_EXIT = 300,
    machinetalk_ContainerType_MT_RTAPI_APP_PING = 301,
    machinetalk_ContainerType_MT_RTAPI_APP_LOADRT = 302,
    machinetalk_ContainerType_MT_RTAPI_APP_LOG = 303,
    machinetalk_ContainerType_MT_RTAPI_APP_UNLOADRT = 305,
    machinetalk_ContainerType_MT_RTAPI_APP_NEWINST = 306,
    machinetalk_ContainerType_MT_RTAPI_APP_NEWTHREAD = 307,
    machinetalk_ContainerType_MT_RTAPI_APP_DELTHREAD = 308,
    machinetalk_ContainerType_MT_RTAPI_APP_CALLFUNC = 309,
    machinetalk_ContainerType_MT_RTAPI_APP_REPLY = 310,
    machinetalk_ContainerType_MT_RTAPI_APP_DELINST = 311,
    machinetalk_ContainerType_MT_LIST_APPLICATIONS = 350,
    machinetalk_ContainerType_MT_DESCRIBE_APPLICATION = 351,
    machinetalk_ContainerType_MT_RETRIEVE_APPLICATION = 352,
    machinetalk_ContainerType_MT_APPLICATION_DETAIL = 353,
    machinetalk_ContainerType_MT_ERROR = 360,
    machinetalk_ContainerType_MT_FULL_UPDATE = 370,
    machinetalk_ContainerType_MT_INCREMENTAL_UPDATE = 371,
    machinetalk_ContainerType_MT_TASK_REPLY = 400,
    machinetalk_ContainerType_MT_TICKET_UPDATE = 401,
    machinetalk_ContainerType_MT_CREDIT_UPDATE = 450,
    machinetalk_ContainerType_MT_EMCMOT_LOWER = 1000,
    machinetalk_ContainerType_MT_EMCMOT_UPPER = 1100,
    machinetalk_ContainerType_MT_EMCMOT_ABORT = 1001,
    machinetalk_ContainerType_MT_EMCMOT_AXIS_ABORT = 1002,
    machinetalk_ContainerType_MT_EMCMOT_ENABLE = 1003,
    machinetalk_ContainerType_MT_EMCMOT_DISABLE = 1004,
    machinetalk_ContainerType_MT_EMCMOT_ENABLE_AMPLIFIER = 1005,
    machinetalk_ContainerType_MT_EMCMOT_DISABLE_AMPLIFIER = 1006,
    machinetalk_ContainerType_MT_EMCMOT_ENABLE_WATCHDOG = 1007,
    machinetalk_ContainerType_MT_EMCMOT_DISABLE_WATCHDOG = 1008,
    machinetalk_ContainerType_MT_EMCMOT_ACTIVATE_JOINT = 1009,
    machinetalk_ContainerType_MT_EMCMOT_DEACTIVATE_JOINT = 1010,
    machinetalk_ContainerType_MT_EMCMOT_PAUSE = 1011,
    machinetalk_ContainerType_MT_EMCMOT_RESUME = 1012,
    machinetalk_ContainerType_MT_EMCMOT_STEP = 1013,
    machinetalk_ContainerType_MT_EMCMOT_FREE = 1014,
    machinetalk_ContainerType_MT_EMCMOT_COORD = 1015,
    machinetalk_ContainerType_MT_EMCMOT_TELEOP = 1016,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_SCALE = 1017,
    machinetalk_ContainerType_MT_EMCMOT_SS_ENABLE = 1018,
    machinetalk_ContainerType_MT_EMCMOT_FEED_SCALE = 1019,
    machinetalk_ContainerType_MT_EMCMOT_FS_ENABLE = 1020,
    machinetalk_ContainerType_MT_EMCMOT_FH_ENABLE = 1021,
    machinetalk_ContainerType_MT_EMCMOT_AF_ENABLE = 1022,
    machinetalk_ContainerType_MT_EMCMOT_OVERRIDE_LIMITS = 1023,
    machinetalk_ContainerType_MT_EMCMOT_HOME = 1024,
    machinetalk_ContainerType_MT_EMCMOT_UNHOME = 1025,
    machinetalk_ContainerType_MT_EMCMOT_JOG_CONT = 1026,
    machinetalk_ContainerType_MT_EMCMOT_JOG_INCR = 1027,
    machinetalk_ContainerType_MT_EMCMOT_JOG_ABS = 1028,
    machinetalk_ContainerType_MT_EMCMOT_SET_LINE = 1029,
    machinetalk_ContainerType_MT_EMCMOT_SET_CIRCLE = 1030,
    machinetalk_ContainerType_MT_EMCMOT_SET_TELEOP_VECTOR = 1031,
    machinetalk_ContainerType_MT_EMCMOT_CLEAR_PROBE_FLAGS = 1032,
    machinetalk_ContainerType_MT_EMCMOT_PROBE = 1033,
    machinetalk_ContainerType_MT_EMCMOT_RIGID_TAP = 1034,
    machinetalk_ContainerType_MT_EMCMOT_SET_POSITION_LIMITS = 1035,
    machinetalk_ContainerType_MT_EMCMOT_SET_BACKLASH = 1036,
    machinetalk_ContainerType_MT_EMCMOT_SET_MIN_FERROR = 1037,
    machinetalk_ContainerType_MT_EMCMOT_SET_MAX_FERROR = 1038,
    machinetalk_ContainerType_MT_EMCMOT_SET_VEL = 1039,
    machinetalk_ContainerType_MT_EMCMOT_SET_VEL_LIMIT = 1040,
    machinetalk_ContainerType_MT_EMCMOT_SET_JOINT_VEL_LIMIT = 1041,
    machinetalk_ContainerType_MT_EMCMOT_SET_JOINT_ACC_LIMIT = 1042,
    machinetalk_ContainerType_MT_EMCMOT_SET_ACC = 1043,
    machinetalk_ContainerType_MT_EMCMOT_SET_TERM_COND = 1044,
    machinetalk_ContainerType_MT_EMCMOT_SET_NUM_AXES = 1045,
    machinetalk_ContainerType_MT_EMCMOT_SET_WORLD_HOME = 1046,
    machinetalk_ContainerType_MT_EMCMOT_SET_HOMING_PARAMS = 1047,
    machinetalk_ContainerType_MT_EMCMOT_SET_DEBUG = 1048,
    machinetalk_ContainerType_MT_EMCMOT_SET_DOUT = 1049,
    machinetalk_ContainerType_MT_EMCMOT_SET_AOUT = 1050,
    machinetalk_ContainerType_MT_EMCMOT_SET_SPINDLESYNC = 1051,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_ON = 1052,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_OFF = 1053,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_INCREASE = 1054,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_DECREASE = 1055,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_BRAKE_ENGAGE = 1056,
    machinetalk_ContainerType_MT_EMCMOT_SPINDLE_BRAKE_RELEASE = 1057,
    machinetalk_ContainerType_MT_EMCMOT_SET_MOTOR_OFFSET = 1058,
    machinetalk_ContainerType_MT_EMCMOT_SET_JOINT_COMP = 1059,
    machinetalk_ContainerType_MT_EMCMOT_SET_OFFSET = 1060,
    machinetalk_ContainerType_MT_EMCMOT_COMMAND_OK = 1061,
    machinetalk_ContainerType_MT_EMCMOT_COMMAND_UNKNOWN_COMMAND = 1062,
    machinetalk_ContainerType_MT_EMCMOT_COMMAND_INVALID_COMMAND = 1063,
    machinetalk_ContainerType_MT_EMCMOT_COMMAND_INVALID_PARAMS = 1064,
    machinetalk_ContainerType_MT_EMCMOT_COMMAND_BAD_EXEC = 1065,
    machinetalk_ContainerType_MT_EMCMOT_MOTION_DISABLED = 1066,
    machinetalk_ContainerType_MT_EMCMOT_MOTION_FREE = 1067,
    machinetalk_ContainerType_MT_EMCMOT_MOTION_TELEOP = 1068,
    machinetalk_ContainerType_MT_EMCMOT_MOTION_COORD = 1069,
    machinetalk_ContainerType_MT_EMCMOT_JOINT_FLAG = 1070,
    machinetalk_ContainerType_MT_EMCMOT_MOTION_FLAG = 1071,
    machinetalk_ContainerType_MT_PRU_FIRMWARE = 2048,
    machinetalk_ContainerType_MT_MESA_5I20_FIRMWARE = 3000,
    machinetalk_ContainerType_MT_BLOB = 4000,
    machinetalk_ContainerType_MT_TEST1 = 5001,
    machinetalk_ContainerType_MT_TEST2 = 5002,
    machinetalk_ContainerType_MT_TEST3 = 5003,
    machinetalk_ContainerType_MT_EMC_NML_LOWER = 10000,
    machinetalk_ContainerType_MT_EMC_NML_UPPER = 13000,
    machinetalk_ContainerType_MT_EMC_OPERATOR_ERROR = 10011,
    machinetalk_ContainerType_MT_EMC_OPERATOR_TEXT = 10012,
    machinetalk_ContainerType_MT_EMC_OPERATOR_DISPLAY = 10013,
    machinetalk_ContainerType_MT_EMC_NULL = 10021,
    machinetalk_ContainerType_MT_EMC_SET_DEBUG = 10022,
    machinetalk_ContainerType_MT_EMC_SYSTEM_CMD = 10030,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_AXIS = 10101,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_UNITS = 10102,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_MIN_POSITION_LIMIT = 10107,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_MAX_POSITION_LIMIT = 10108,
    machinetalk_ContainerType_MT_EMC_TOOL_START_CHANGE = 1110,
    machinetalk_ContainerType_MT_EMC_EXEC_PLUGIN_CALL = 1112,
    machinetalk_ContainerType_MT_EMC_IO_PLUGIN_CALL = 1113,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_FERROR = 10111,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_HOMING_PARAMS = 10112,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_MIN_FERROR = 10115,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_MAX_VELOCITY = 10116,
    machinetalk_ContainerType_MT_EMC_AXIS_INIT = 10118,
    machinetalk_ContainerType_MT_EMC_AXIS_HALT = 10119,
    machinetalk_ContainerType_MT_EMC_AXIS_ABORT = 10120,
    machinetalk_ContainerType_MT_EMC_AXIS_ENABLE = 10121,
    machinetalk_ContainerType_MT_EMC_AXIS_DISABLE = 10122,
    machinetalk_ContainerType_MT_EMC_AXIS_HOME = 10123,
    machinetalk_ContainerType_MT_EMC_AXIS_UNHOME = 10135,
    machinetalk_ContainerType_MT_EMC_AXIS_JOG = 10124,
    machinetalk_ContainerType_MT_EMC_AXIS_INCR_JOG = 10125,
    machinetalk_ContainerType_MT_EMC_AXIS_ABS_JOG = 10126,
    machinetalk_ContainerType_MT_EMC_AXIS_ACTIVATE = 10127,
    machinetalk_ContainerType_MT_EMC_AXIS_DEACTIVATE = 10128,
    machinetalk_ContainerType_MT_EMC_AXIS_OVERRIDE_LIMITS = 10129,
    machinetalk_ContainerType_MT_EMC_AXIS_LOAD_COMP = 10131,
    machinetalk_ContainerType_MT_EMC_AXIS_SET_BACKLASH = 10134,
    machinetalk_ContainerType_MT_EMC_AXIS_STAT = 10199,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_AXES = 10201,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_UNITS = 10202,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_CYCLE_TIME = 10203,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_MODE = 10204,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_VELOCITY = 10205,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_ACCELERATION = 10206,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_MAX_VELOCITY = 10207,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_MAX_ACCELERATION = 10208,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_SCALE = 10209,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_MOTION_ID = 10210,
    machinetalk_ContainerType_MT_EMC_TRAJ_INIT = 10211,
    machinetalk_ContainerType_MT_EMC_TRAJ_HALT = 10212,
    machinetalk_ContainerType_MT_EMC_TRAJ_ENABLE = 10213,
    machinetalk_ContainerType_MT_EMC_TRAJ_DISABLE = 10214,
    machinetalk_ContainerType_MT_EMC_TRAJ_ABORT = 10215,
    machinetalk_ContainerType_MT_EMC_TRAJ_PAUSE = 10216,
    machinetalk_ContainerType_MT_EMC_TRAJ_STEP = 10217,
    machinetalk_ContainerType_MT_EMC_TRAJ_RESUME = 10218,
    machinetalk_ContainerType_MT_EMC_TRAJ_DELAY = 10219,
    machinetalk_ContainerType_MT_EMC_TRAJ_LINEAR_MOVE = 10220,
    machinetalk_ContainerType_MT_EMC_TRAJ_CIRCULAR_MOVE = 10221,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_TERM_COND = 10222,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_OFFSET = 10223,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_G5X = 10224,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_HOME = 10225,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_ROTATION = 10226,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_G92 = 10227,
    machinetalk_ContainerType_MT_EMC_TRAJ_CLEAR_PROBE_TRIPPED_FLAG = 10228,
    machinetalk_ContainerType_MT_EMC_TRAJ_PROBE = 10229,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_TELEOP_ENABLE = 10230,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_TELEOP_VECTOR = 10231,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_SPINDLESYNC = 10232,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_SPINDLE_SCALE = 10233,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_FO_ENABLE = 10234,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_SO_ENABLE = 10235,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_FH_ENABLE = 10236,
    machinetalk_ContainerType_MT_EMC_TRAJ_RIGID_TAP = 10237,
    machinetalk_ContainerType_MT_EMC_TRAJ_SET_RAPID_SCALE = 10238,
    machinetalk_ContainerType_MT_EMC_TRAJ_STAT = 10299,
    machinetalk_ContainerType_MT_EMC_MOTION_INIT = 10301,
    machinetalk_ContainerType_MT_EMC_MOTION_HALT = 10302,
    machinetalk_ContainerType_MT_EMC_MOTION_ABORT = 10303,
    machinetalk_ContainerType_MT_EMC_MOTION_SET_AOUT = 10304,
    machinetalk_ContainerType_MT_EMC_MOTION_SET_DOUT = 10305,
    machinetalk_ContainerType_MT_EMC_MOTION_ADAPTIVE = 10306,
    machinetalk_ContainerType_MT_EMC_SPINDLE_ORIENT = 10317,
    machinetalk_ContainerType_MT_EMC_SPINDLE_WAIT_ORIENT_COMPLETE = 10318,
    machinetalk_ContainerType_MT_EMC_MOTION_STAT = 10399,
    machinetalk_ContainerType_MT_EMC_TASK_INIT = 10501,
    machinetalk_ContainerType_MT_EMC_TASK_HALT = 10502,
    machinetalk_ContainerType_MT_EMC_TASK_ABORT = 10503,
    machinetalk_ContainerType_MT_EMC_TASK_SET_MODE = 10504,
    machinetalk_ContainerType_MT_EMC_TASK_SET_STATE = 10505,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_OPEN = 10506,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_RUN = 10507,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_READ = 10508,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_EXECUTE = 10509,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_PAUSE = 10510,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_STEP = 10511,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_RESUME = 10512,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_END = 10513,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_CLOSE = 10514,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_INIT = 10515,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_SYNCH = 10516,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_SET_OPTIONAL_STOP = 10517,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_SET_BLOCK_DELETE = 10518,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_OPTIONAL_STOP = 10519,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_RESET = 10520,
    machinetalk_ContainerType_MT_EMC_TASK_PLAN_REPLY = 10530,
    machinetalk_ContainerType_MT_EMC_TASK_STAT = 10599,
    machinetalk_ContainerType_MT_EMC_TOOL_INIT = 11101,
    machinetalk_ContainerType_MT_EMC_TOOL_HALT = 11102,
    machinetalk_ContainerType_MT_EMC_TOOL_ABORT = 11103,
    machinetalk_ContainerType_MT_EMC_TOOL_PREPARE = 11104,
    machinetalk_ContainerType_MT_EMC_TOOL_LOAD = 11105,
    machinetalk_ContainerType_MT_EMC_TOOL_UNLOAD = 11106,
    machinetalk_ContainerType_MT_EMC_TOOL_LOAD_TOOL_TABLE = 11107,
    machinetalk_ContainerType_MT_EMC_TOOL_SET_OFFSET = 11108,
    machinetalk_ContainerType_MT_EMC_TOOL_SET_NUMBER = 11109,
    machinetalk_ContainerType_MT_EMC_TOOL_UPDATE_TOOL_TABLE = 11110,
    machinetalk_ContainerType_MT_EMC_TOOL_STAT = 11199,
    machinetalk_ContainerType_MT_EMC_AUX_ESTOP_ON = 11206,
    machinetalk_ContainerType_MT_EMC_AUX_ESTOP_OFF = 11207,
    machinetalk_ContainerType_MT_EMC_AUX_ESTOP_RESET = 11208,
    machinetalk_ContainerType_MT_EMC_AUX_INPUT_WAIT = 11209,
    machinetalk_ContainerType_MT_EMC_AUX_STAT = 11299,
    machinetalk_ContainerType_MT_EMC_SPINDLE_ON = 11304,
    machinetalk_ContainerType_MT_EMC_SPINDLE_OFF = 11305,
    machinetalk_ContainerType_MT_EMC_SPINDLE_INCREASE = 11309,
    machinetalk_ContainerType_MT_EMC_SPINDLE_DECREASE = 11310,
    machinetalk_ContainerType_MT_EMC_SPINDLE_CONSTANT = 11311,
    machinetalk_ContainerType_MT_EMC_SPINDLE_BRAKE_RELEASE = 11312,
    machinetalk_ContainerType_MT_EMC_SPINDLE_BRAKE_ENGAGE = 11313,
    machinetalk_ContainerType_MT_EMC_SPINDLE_SPEED = 11316,
    machinetalk_ContainerType_MT_EMC_SPINDLE_STAT = 11399,
    machinetalk_ContainerType_MT_EMC_COOLANT_MIST_ON = 11404,
    machinetalk_ContainerType_MT_EMC_COOLANT_MIST_OFF = 11405,
    machinetalk_ContainerType_MT_EMC_COOLANT_FLOOD_ON = 11406,
    machinetalk_ContainerType_MT_EMC_COOLANT_FLOOD_OFF = 11407,
    machinetalk_ContainerType_MT_EMC_COOLANT_STAT = 11499,
    machinetalk_ContainerType_MT_EMC_LUBE_ON = 11504,
    machinetalk_ContainerType_MT_EMC_LUBE_OFF = 11505,
    machinetalk_ContainerType_MT_EMC_LUBE_STAT = 11599,
    machinetalk_ContainerType_MT_EMC_IO_INIT = 11601,
    machinetalk_ContainerType_MT_EMC_IO_HALT = 11602,
    machinetalk_ContainerType_MT_EMC_IO_ABORT = 11603,
    machinetalk_ContainerType_MT_EMC_IO_SET_CYCLE_TIME = 11604,
    machinetalk_ContainerType_MT_EMC_IO_STAT = 11699,
    machinetalk_ContainerType_MT_EMC_INIT = 11901,
    machinetalk_ContainerType_MT_EMC_HALT = 11902,
    machinetalk_ContainerType_MT_EMC_ABORT = 11903,
    machinetalk_ContainerType_MT_EMC_STAT = 11999,
    machinetalk_ContainerType_MT_EMCSTAT_FULL_UPDATE = 12500,
    machinetalk_ContainerType_MT_EMCSTAT_INCREMENTAL_UPDATE = 12501,
    machinetalk_ContainerType_MT_EMC_NML_ERROR = 12510,
    machinetalk_ContainerType_MT_EMC_NML_TEXT = 12511,
    machinetalk_ContainerType_MT_EMC_NML_DISPLAY = 12512,
    machinetalk_ContainerType_MT_EMCCMD_EXECUTED = 12520,
    machinetalk_ContainerType_MT_EMCCMD_COMPLETED = 12521,
    machinetalk_ContainerType_MT_LAUNCHER_FULL_UPDATE = 12600,
    machinetalk_ContainerType_MT_LAUNCHER_INCREMENTAL_UPDATE = 12601,
    machinetalk_ContainerType_MT_LAUNCHER_ERROR = 12602,
    machinetalk_ContainerType_MT_LAUNCHER_START = 12610,
    machinetalk_ContainerType_MT_LAUNCHER_TERMINATE = 12611,
    machinetalk_ContainerType_MT_LAUNCHER_KILL = 12612,
    machinetalk_ContainerType_MT_LAUNCHER_WRITE_STDIN = 12613,
    machinetalk_ContainerType_MT_LAUNCHER_CALL = 12614,
    machinetalk_ContainerType_MT_LAUNCHER_SHUTDOWN = 12615
} machinetalk_ContainerType;

typedef enum _machinetalk_OriginIndex {
    machinetalk_OriginIndex_ORIGIN_UNKNOWN = 0,
    machinetalk_OriginIndex_ORIGIN_G54 = 1,
    machinetalk_OriginIndex_ORIGIN_G55 = 2,
    machinetalk_OriginIndex_ORIGIN_G56 = 3,
    machinetalk_OriginIndex_ORIGIN_G57 = 4,
    machinetalk_OriginIndex_ORIGIN_G58 = 5,
    machinetalk_OriginIndex_ORIGIN_G59 = 6,
    machinetalk_OriginIndex_ORIGIN_G59_1 = 7,
    machinetalk_OriginIndex_ORIGIN_G59_2 = 8,
    machinetalk_OriginIndex_ORIGIN_G59_3 = 9
} machinetalk_OriginIndex;

typedef enum _machinetalk_TermConditionType {
    machinetalk_TermConditionType__EMC_TRAJ_TERM_COND_STOP = 1,
    machinetalk_TermConditionType__EMC_TRAJ_TERM_COND_BLEND = 2
} machinetalk_TermConditionType;

typedef enum _machinetalk_CanonDirection {
    machinetalk_CanonDirection__CANON_STOPPED = 1,
    machinetalk_CanonDirection__CANON_CLOCKWISE = 2,
    machinetalk_CanonDirection__CANON_COUNTERCLOCKWISE = 3
} machinetalk_CanonDirection;

typedef enum _machinetalk_InputType {
    machinetalk_InputType__ANALOG_INPUT = 0,
    machinetalk_InputType__DIGITAL_INPUT = 1
} machinetalk_InputType;

typedef enum _machinetalk_WaitType {
    machinetalk_WaitType_IMMEDIATE = 0,
    machinetalk_WaitType_RISE = 1,
    machinetalk_WaitType_FALL = 2,
    machinetalk_WaitType_BE_HIGH = 3,
    machinetalk_WaitType_BE_LOW = 4
} machinetalk_WaitType;

typedef enum _machinetalk_InterpreterStateType {
    machinetalk_InterpreterStateType_INTERP_IDLE = 1,
    machinetalk_InterpreterStateType_INTERP_RUNNING = 2,
    machinetalk_InterpreterStateType_INTERP_SYNC_WAIT = 3,
    machinetalk_InterpreterStateType_INTERP_PAUSED = 4,
    machinetalk_InterpreterStateType_INTERP_QUEUE_WAIT = 5,
    machinetalk_InterpreterStateType_INTERP_ABORT_WAIT = 6,
    machinetalk_InterpreterStateType_INTERP_STATE_UNSET = 99
} machinetalk_InterpreterStateType;

/* Struct definitions */
/* Default values for struct fields */

/* Initializer values for message structs */

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */

/* Maximum encoded size of messages (where known) */

/* helper macros for message type ids if set with */
/* option (nanopb_msgopt).msgid = <id>; */

#ifdef PB_MSGID

#define TYPES_MESSAGES \

#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
