// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: machinetalk/protobuf/value.proto

#ifndef PROTOBUF_machinetalk_2fprotobuf_2fvalue_2eproto__INCLUDED
#define PROTOBUF_machinetalk_2fprotobuf_2fvalue_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "machinetalk/protobuf/nanopb.pb.h"
#include "machinetalk/protobuf/emcclass.pb.h"
#include "machinetalk/protobuf/types.pb.h"
// @@protoc_insertion_point(includes)

namespace machinetalk {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_machinetalk_2fprotobuf_2fvalue_2eproto();
void protobuf_AssignDesc_machinetalk_2fprotobuf_2fvalue_2eproto();
void protobuf_ShutdownFile_machinetalk_2fprotobuf_2fvalue_2eproto();

class Value;

// ===================================================================

class Value : public ::google::protobuf::Message {
 public:
  Value();
  virtual ~Value();

  Value(const Value& from);

  inline Value& operator=(const Value& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Value& default_instance();

  void Swap(Value* other);

  // implements Message ----------------------------------------------

  Value* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Value& from);
  void MergeFrom(const Value& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .machinetalk.ValueType type = 10;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 10;
  inline ::machinetalk::ValueType type() const;
  inline void set_type(::machinetalk::ValueType value);

  // optional bool halbit = 100;
  inline bool has_halbit() const;
  inline void clear_halbit();
  static const int kHalbitFieldNumber = 100;
  inline bool halbit() const;
  inline void set_halbit(bool value);

  // optional double halfloat = 101;
  inline bool has_halfloat() const;
  inline void clear_halfloat();
  static const int kHalfloatFieldNumber = 101;
  inline double halfloat() const;
  inline void set_halfloat(double value);

  // optional sfixed32 hals32 = 102;
  inline bool has_hals32() const;
  inline void clear_hals32();
  static const int kHals32FieldNumber = 102;
  inline ::google::protobuf::int32 hals32() const;
  inline void set_hals32(::google::protobuf::int32 value);

  // optional fixed32 halu32 = 103;
  inline bool has_halu32() const;
  inline void clear_halu32();
  static const int kHalu32FieldNumber = 103;
  inline ::google::protobuf::uint32 halu32() const;
  inline void set_halu32(::google::protobuf::uint32 value);

  // optional bytes v_bytes = 120;
  inline bool has_v_bytes() const;
  inline void clear_v_bytes();
  static const int kVBytesFieldNumber = 120;
  inline const ::std::string& v_bytes() const;
  inline void set_v_bytes(const ::std::string& value);
  inline void set_v_bytes(const char* value);
  inline void set_v_bytes(const void* value, size_t size);
  inline ::std::string* mutable_v_bytes();
  inline ::std::string* release_v_bytes();
  inline void set_allocated_v_bytes(::std::string* v_bytes);

  // optional sfixed32 v_int32 = 130;
  inline bool has_v_int32() const;
  inline void clear_v_int32();
  static const int kVInt32FieldNumber = 130;
  inline ::google::protobuf::int32 v_int32() const;
  inline void set_v_int32(::google::protobuf::int32 value);

  // optional sfixed64 v_int64 = 140;
  inline bool has_v_int64() const;
  inline void clear_v_int64();
  static const int kVInt64FieldNumber = 140;
  inline ::google::protobuf::int64 v_int64() const;
  inline void set_v_int64(::google::protobuf::int64 value);

  // optional fixed32 v_uint32 = 150;
  inline bool has_v_uint32() const;
  inline void clear_v_uint32();
  static const int kVUint32FieldNumber = 150;
  inline ::google::protobuf::uint32 v_uint32() const;
  inline void set_v_uint32(::google::protobuf::uint32 value);

  // optional fixed64 v_uint64 = 160;
  inline bool has_v_uint64() const;
  inline void clear_v_uint64();
  static const int kVUint64FieldNumber = 160;
  inline ::google::protobuf::uint64 v_uint64() const;
  inline void set_v_uint64(::google::protobuf::uint64 value);

  // optional double v_double = 170;
  inline bool has_v_double() const;
  inline void clear_v_double();
  static const int kVDoubleFieldNumber = 170;
  inline double v_double() const;
  inline void set_v_double(double value);

  // optional string v_string = 180;
  inline bool has_v_string() const;
  inline void clear_v_string();
  static const int kVStringFieldNumber = 180;
  inline const ::std::string& v_string() const;
  inline void set_v_string(const ::std::string& value);
  inline void set_v_string(const char* value);
  inline void set_v_string(const char* value, size_t size);
  inline ::std::string* mutable_v_string();
  inline ::std::string* release_v_string();
  inline void set_allocated_v_string(::std::string* v_string);

  // optional bool v_bool = 190;
  inline bool has_v_bool() const;
  inline void clear_v_bool();
  static const int kVBoolFieldNumber = 190;
  inline bool v_bool() const;
  inline void set_v_bool(bool value);

  // optional .machinetalk.PmCartesian carte = 200;
  inline bool has_carte() const;
  inline void clear_carte();
  static const int kCarteFieldNumber = 200;
  inline const ::machinetalk::PmCartesian& carte() const;
  inline ::machinetalk::PmCartesian* mutable_carte();
  inline ::machinetalk::PmCartesian* release_carte();
  inline void set_allocated_carte(::machinetalk::PmCartesian* carte);

  // optional .machinetalk.EmcPose pose = 220;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 220;
  inline const ::machinetalk::EmcPose& pose() const;
  inline ::machinetalk::EmcPose* mutable_pose();
  inline ::machinetalk::EmcPose* release_pose();
  inline void set_allocated_pose(::machinetalk::EmcPose* pose);

  // @@protoc_insertion_point(class_scope:machinetalk.Value)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_halbit();
  inline void clear_has_halbit();
  inline void set_has_halfloat();
  inline void clear_has_halfloat();
  inline void set_has_hals32();
  inline void clear_has_hals32();
  inline void set_has_halu32();
  inline void clear_has_halu32();
  inline void set_has_v_bytes();
  inline void clear_has_v_bytes();
  inline void set_has_v_int32();
  inline void clear_has_v_int32();
  inline void set_has_v_int64();
  inline void clear_has_v_int64();
  inline void set_has_v_uint32();
  inline void clear_has_v_uint32();
  inline void set_has_v_uint64();
  inline void clear_has_v_uint64();
  inline void set_has_v_double();
  inline void clear_has_v_double();
  inline void set_has_v_string();
  inline void clear_has_v_string();
  inline void set_has_v_bool();
  inline void clear_has_v_bool();
  inline void set_has_carte();
  inline void clear_has_carte();
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::int32 hals32_;
  double halfloat_;
  ::std::string* v_bytes_;
  ::google::protobuf::uint32 halu32_;
  ::google::protobuf::int32 v_int32_;
  ::google::protobuf::int64 v_int64_;
  bool halbit_;
  bool v_bool_;
  ::google::protobuf::uint32 v_uint32_;
  ::google::protobuf::uint64 v_uint64_;
  double v_double_;
  ::std::string* v_string_;
  ::machinetalk::PmCartesian* carte_;
  ::machinetalk::EmcPose* pose_;
  friend void  protobuf_AddDesc_machinetalk_2fprotobuf_2fvalue_2eproto();
  friend void protobuf_AssignDesc_machinetalk_2fprotobuf_2fvalue_2eproto();
  friend void protobuf_ShutdownFile_machinetalk_2fprotobuf_2fvalue_2eproto();

  void InitAsDefaultInstance();
  static Value* default_instance_;
};
// ===================================================================


// ===================================================================

// Value

// required .machinetalk.ValueType type = 10;
inline bool Value::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Value::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Value::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Value::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::machinetalk::ValueType Value::type() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.type)
  return static_cast< ::machinetalk::ValueType >(type_);
}
inline void Value::set_type(::machinetalk::ValueType value) {
  assert(::machinetalk::ValueType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.type)
}

// optional bool halbit = 100;
inline bool Value::has_halbit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Value::set_has_halbit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Value::clear_has_halbit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Value::clear_halbit() {
  halbit_ = false;
  clear_has_halbit();
}
inline bool Value::halbit() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.halbit)
  return halbit_;
}
inline void Value::set_halbit(bool value) {
  set_has_halbit();
  halbit_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.halbit)
}

// optional double halfloat = 101;
inline bool Value::has_halfloat() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Value::set_has_halfloat() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Value::clear_has_halfloat() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Value::clear_halfloat() {
  halfloat_ = 0;
  clear_has_halfloat();
}
inline double Value::halfloat() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.halfloat)
  return halfloat_;
}
inline void Value::set_halfloat(double value) {
  set_has_halfloat();
  halfloat_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.halfloat)
}

// optional sfixed32 hals32 = 102;
inline bool Value::has_hals32() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Value::set_has_hals32() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Value::clear_has_hals32() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Value::clear_hals32() {
  hals32_ = 0;
  clear_has_hals32();
}
inline ::google::protobuf::int32 Value::hals32() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.hals32)
  return hals32_;
}
inline void Value::set_hals32(::google::protobuf::int32 value) {
  set_has_hals32();
  hals32_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.hals32)
}

// optional fixed32 halu32 = 103;
inline bool Value::has_halu32() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Value::set_has_halu32() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Value::clear_has_halu32() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Value::clear_halu32() {
  halu32_ = 0u;
  clear_has_halu32();
}
inline ::google::protobuf::uint32 Value::halu32() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.halu32)
  return halu32_;
}
inline void Value::set_halu32(::google::protobuf::uint32 value) {
  set_has_halu32();
  halu32_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.halu32)
}

// optional bytes v_bytes = 120;
inline bool Value::has_v_bytes() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Value::set_has_v_bytes() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Value::clear_has_v_bytes() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Value::clear_v_bytes() {
  if (v_bytes_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_bytes_->clear();
  }
  clear_has_v_bytes();
}
inline const ::std::string& Value::v_bytes() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_bytes)
  return *v_bytes_;
}
inline void Value::set_v_bytes(const ::std::string& value) {
  set_has_v_bytes();
  if (v_bytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_bytes_ = new ::std::string;
  }
  v_bytes_->assign(value);
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_bytes)
}
inline void Value::set_v_bytes(const char* value) {
  set_has_v_bytes();
  if (v_bytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_bytes_ = new ::std::string;
  }
  v_bytes_->assign(value);
  // @@protoc_insertion_point(field_set_char:machinetalk.Value.v_bytes)
}
inline void Value::set_v_bytes(const void* value, size_t size) {
  set_has_v_bytes();
  if (v_bytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_bytes_ = new ::std::string;
  }
  v_bytes_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:machinetalk.Value.v_bytes)
}
inline ::std::string* Value::mutable_v_bytes() {
  set_has_v_bytes();
  if (v_bytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_bytes_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:machinetalk.Value.v_bytes)
  return v_bytes_;
}
inline ::std::string* Value::release_v_bytes() {
  clear_has_v_bytes();
  if (v_bytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = v_bytes_;
    v_bytes_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Value::set_allocated_v_bytes(::std::string* v_bytes) {
  if (v_bytes_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete v_bytes_;
  }
  if (v_bytes) {
    set_has_v_bytes();
    v_bytes_ = v_bytes;
  } else {
    clear_has_v_bytes();
    v_bytes_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:machinetalk.Value.v_bytes)
}

// optional sfixed32 v_int32 = 130;
inline bool Value::has_v_int32() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Value::set_has_v_int32() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Value::clear_has_v_int32() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Value::clear_v_int32() {
  v_int32_ = 0;
  clear_has_v_int32();
}
inline ::google::protobuf::int32 Value::v_int32() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_int32)
  return v_int32_;
}
inline void Value::set_v_int32(::google::protobuf::int32 value) {
  set_has_v_int32();
  v_int32_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_int32)
}

// optional sfixed64 v_int64 = 140;
inline bool Value::has_v_int64() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Value::set_has_v_int64() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Value::clear_has_v_int64() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Value::clear_v_int64() {
  v_int64_ = GOOGLE_LONGLONG(0);
  clear_has_v_int64();
}
inline ::google::protobuf::int64 Value::v_int64() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_int64)
  return v_int64_;
}
inline void Value::set_v_int64(::google::protobuf::int64 value) {
  set_has_v_int64();
  v_int64_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_int64)
}

// optional fixed32 v_uint32 = 150;
inline bool Value::has_v_uint32() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Value::set_has_v_uint32() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Value::clear_has_v_uint32() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Value::clear_v_uint32() {
  v_uint32_ = 0u;
  clear_has_v_uint32();
}
inline ::google::protobuf::uint32 Value::v_uint32() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_uint32)
  return v_uint32_;
}
inline void Value::set_v_uint32(::google::protobuf::uint32 value) {
  set_has_v_uint32();
  v_uint32_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_uint32)
}

// optional fixed64 v_uint64 = 160;
inline bool Value::has_v_uint64() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Value::set_has_v_uint64() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Value::clear_has_v_uint64() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Value::clear_v_uint64() {
  v_uint64_ = GOOGLE_ULONGLONG(0);
  clear_has_v_uint64();
}
inline ::google::protobuf::uint64 Value::v_uint64() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_uint64)
  return v_uint64_;
}
inline void Value::set_v_uint64(::google::protobuf::uint64 value) {
  set_has_v_uint64();
  v_uint64_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_uint64)
}

// optional double v_double = 170;
inline bool Value::has_v_double() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void Value::set_has_v_double() {
  _has_bits_[0] |= 0x00000400u;
}
inline void Value::clear_has_v_double() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void Value::clear_v_double() {
  v_double_ = 0;
  clear_has_v_double();
}
inline double Value::v_double() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_double)
  return v_double_;
}
inline void Value::set_v_double(double value) {
  set_has_v_double();
  v_double_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_double)
}

// optional string v_string = 180;
inline bool Value::has_v_string() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void Value::set_has_v_string() {
  _has_bits_[0] |= 0x00000800u;
}
inline void Value::clear_has_v_string() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void Value::clear_v_string() {
  if (v_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_string_->clear();
  }
  clear_has_v_string();
}
inline const ::std::string& Value::v_string() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_string)
  return *v_string_;
}
inline void Value::set_v_string(const ::std::string& value) {
  set_has_v_string();
  if (v_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_string_ = new ::std::string;
  }
  v_string_->assign(value);
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_string)
}
inline void Value::set_v_string(const char* value) {
  set_has_v_string();
  if (v_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_string_ = new ::std::string;
  }
  v_string_->assign(value);
  // @@protoc_insertion_point(field_set_char:machinetalk.Value.v_string)
}
inline void Value::set_v_string(const char* value, size_t size) {
  set_has_v_string();
  if (v_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_string_ = new ::std::string;
  }
  v_string_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:machinetalk.Value.v_string)
}
inline ::std::string* Value::mutable_v_string() {
  set_has_v_string();
  if (v_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    v_string_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:machinetalk.Value.v_string)
  return v_string_;
}
inline ::std::string* Value::release_v_string() {
  clear_has_v_string();
  if (v_string_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = v_string_;
    v_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Value::set_allocated_v_string(::std::string* v_string) {
  if (v_string_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete v_string_;
  }
  if (v_string) {
    set_has_v_string();
    v_string_ = v_string;
  } else {
    clear_has_v_string();
    v_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:machinetalk.Value.v_string)
}

// optional bool v_bool = 190;
inline bool Value::has_v_bool() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void Value::set_has_v_bool() {
  _has_bits_[0] |= 0x00001000u;
}
inline void Value::clear_has_v_bool() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void Value::clear_v_bool() {
  v_bool_ = false;
  clear_has_v_bool();
}
inline bool Value::v_bool() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.v_bool)
  return v_bool_;
}
inline void Value::set_v_bool(bool value) {
  set_has_v_bool();
  v_bool_ = value;
  // @@protoc_insertion_point(field_set:machinetalk.Value.v_bool)
}

// optional .machinetalk.PmCartesian carte = 200;
inline bool Value::has_carte() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void Value::set_has_carte() {
  _has_bits_[0] |= 0x00002000u;
}
inline void Value::clear_has_carte() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void Value::clear_carte() {
  if (carte_ != NULL) carte_->::machinetalk::PmCartesian::Clear();
  clear_has_carte();
}
inline const ::machinetalk::PmCartesian& Value::carte() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.carte)
  return carte_ != NULL ? *carte_ : *default_instance_->carte_;
}
inline ::machinetalk::PmCartesian* Value::mutable_carte() {
  set_has_carte();
  if (carte_ == NULL) carte_ = new ::machinetalk::PmCartesian;
  // @@protoc_insertion_point(field_mutable:machinetalk.Value.carte)
  return carte_;
}
inline ::machinetalk::PmCartesian* Value::release_carte() {
  clear_has_carte();
  ::machinetalk::PmCartesian* temp = carte_;
  carte_ = NULL;
  return temp;
}
inline void Value::set_allocated_carte(::machinetalk::PmCartesian* carte) {
  delete carte_;
  carte_ = carte;
  if (carte) {
    set_has_carte();
  } else {
    clear_has_carte();
  }
  // @@protoc_insertion_point(field_set_allocated:machinetalk.Value.carte)
}

// optional .machinetalk.EmcPose pose = 220;
inline bool Value::has_pose() const {
  return (_has_bits_[0] & 0x00004000u) != 0;
}
inline void Value::set_has_pose() {
  _has_bits_[0] |= 0x00004000u;
}
inline void Value::clear_has_pose() {
  _has_bits_[0] &= ~0x00004000u;
}
inline void Value::clear_pose() {
  if (pose_ != NULL) pose_->::machinetalk::EmcPose::Clear();
  clear_has_pose();
}
inline const ::machinetalk::EmcPose& Value::pose() const {
  // @@protoc_insertion_point(field_get:machinetalk.Value.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::machinetalk::EmcPose* Value::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::machinetalk::EmcPose;
  // @@protoc_insertion_point(field_mutable:machinetalk.Value.pose)
  return pose_;
}
inline ::machinetalk::EmcPose* Value::release_pose() {
  clear_has_pose();
  ::machinetalk::EmcPose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void Value::set_allocated_pose(::machinetalk::EmcPose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:machinetalk.Value.pose)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace machinetalk

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_machinetalk_2fprotobuf_2fvalue_2eproto__INCLUDED
