#!/bin/bash -e

# This script will install the python module $1, from source $2, 
# to destination $3.
# If run from Cpack, the setup.py will just be copied to the installation dir.
# $4 is the python executable, $5 is the installation prefix for normal install
# $6 CPACK_PACKAGING_INSTALL_PREFIX

if [ "x$1" != "x" ] && [ "x$2" != "x" ] && [ "x$3" != "x" ]; then
    # check if we're packaging or installing
    if [[ $DESTDIR == *_CPack_Packages* ]]; then
        # update setup.py setup.py just needs to be copied
        if [ -f $2/setup.py ]; then
            echo updating $1/setup.py
            sed "s~_DESTDIR_$5/share/pyshared~$6/share/pyshared~g" $2/setup.py \
                > $DESTDIR/$6/share/pyshared/$1/setup
            rm -f $DESTDIR/$6/share/pyshared/$1/setup.py
        fi
    else
        # run setup script
        if [ -f $2/setup.py ]; then
            echo installing $1/setup.py
            sed "s~_DESTDIR_~$DESTDIR~g" $2/setup.py > $DESTDIR/$3/$1/setup.py
            $4 $DESTDIR/$3/$1/setup.py install --prefix $DESTDIR/$5
            rm -rf $DESTDIR/$3/$1/setup.py
        fi
    fi
fi
