set(CMAKE_SYSTEM_NAME Linux)

# build
if("$ENV{DEB_TARGET_ARCH_CPU}" STREQUAL "i386")
    set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)
elseif("$ENV{DEB_TARGET_ARCH_CPU}" STREQUAL "arm")
    set(CMAKE_C_COMPILER "$ENV{DEB_TARGET_GNU_TYPE}-gcc")
    set(CMAKE_CXX_COMPILER "$ENV{DEB_TARGET_GNU_TYPE}-g++")
endif()

if (DEFINED ENV{DPKG_ROOT})
    set(CMAKE_FIND_ROOT_PATH "$ENV{DPKG_ROOT}")
    set(CMAKE_SYSROOT "$ENV{DPKG_ROOT}")
else()
    set(CMAKE_FIND_ROOT_PATH /sysroot)
    set(CMAKE_SYSROOT /sysroot)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
